### PR TITLE
Update docker package name for Travis

### PR DESCRIPTION
**Pull request by bquenin**
Updates the docker package name for Travis builds.

## How to test
Make sure Travis successfully updates docker.

### CODE REVIEW

**Comment by ndegory** [comment]
what was the issue?

**Comment by bquenin** [comment]
https://travis-ci.org/appcelerator/amp/builds/245511986#L274-L284

**Comment by ndegory** [comment]
from what I see in the build logs, now by default docker is already installed with version 17.03.1 (latest stable, for a few days at least).
we're supposed to be compatible with this version, why should we upgrade to the edge version?

**Comment by bquenin** [comment]
because we used to build against 17.05 until now , so it's just a matter of continuity, I don't mind using 17.03 though

**Review by ndegory — APPROVED** [review]
LGTM
we'll switch to stable channel once 17.06 is released

**Pull request merged**
