### PR TITLE
Vendor dependencies needed for service api

### PR DESCRIPTION
**Pull request by subfuzion**
This PR updates vendor dependencies for the service API.
## Verification

**Doesn't work. See:** https://github.com/appcelerator/amp/pull/138#issuecomment-244827193

```
$ rm -rf ~/.glide .glide vendor
$ make install-deps
$ make build
```

**To verify, run tools on host for now:**

```
$ rm -rf ~/.glide .glide vendor
$ glide install
$ make install
```

### CODE REVIEW

**Comment by bquenin** [comment]
Tested locally but doesn't work on my linux machine.

```
✘  bq@u16  ~/go/src/github.com/appcelerator/amp   vendor-service ± make install-deps
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/cloudfoundry-incubator/candiedyaml.
[INFO]  --> Fetching github.com/coreos/etcd.
[INFO]  --> Fetching github.com/davecgh/go-spew.
[INFO]  --> Fetching github.com/docker/distribution.
[INFO]  --> Fetching github.com/docker/go-connections.
[INFO]  --> Fetching github.com/eapache/go-resiliency.
[INFO]  --> Fetching github.com/docker/go-units.
[INFO]  --> Fetching github.com/eapache/go-xerial-snappy.
[INFO]  --> Fetching github.com/fatih/color.
[INFO]  --> Fetching github.com/ghodss/yaml.
[INFO]  --> Fetching github.com/docker/engine-api.
[INFO]  --> Fetching github.com/gogo/protobuf.
[INFO]  --> Fetching github.com/google/go-github.
[INFO]  --> Fetching github.com/golang/protobuf.
[INFO]  --> Fetching github.com/google/go-querystring.
[INFO]  --> Fetching github.com/fsnotify/fsnotify.
[INFO]  --> Fetching github.com/grpc-ecosystem/grpc-gateway.
[INFO]  --> Fetching github.com/hashicorp/hcl.
[INFO]  --> Fetching github.com/eapache/queue.
[INFO]  --> Fetching github.com/golang/snappy.
[WARN]  Unable to checkout github.com/eapache/go-xerial-snappy
[ERROR] Update failed for github.com/eapache/go-xerial-snappy: Unable to get repository
[INFO]  --> Fetching github.com/howeyc/gopass.
[WARN]  Unable to checkout github.com/eapache/queue
[ERROR] Update failed for github.com/eapache/queue: Unable to get repository
[INFO]  --> Fetching github.com/inconshreveable/mousetrap.
[WARN]  Unable to checkout github.com/google/go-querystring
[ERROR] Update failed for github.com/google/go-querystring: Unable to get repository
[INFO]  --> Fetching github.com/influxdata/influxdb.
[WARN]  Unable to checkout github.com/eapache/go-resiliency
[ERROR] Update failed for github.com/eapache/go-resiliency: Unable to get repository
[INFO]  --> Fetching github.com/klauspost/crc32.
[WARN]  Unable to checkout github.com/ghodss/yaml
[ERROR] Update failed for github.com/ghodss/yaml: Unable to get repository
[INFO]  --> Fetching github.com/kr/fs.
[WARN]  Unable to checkout github.com/docker/go-units
[ERROR] Update failed for github.com/docker/go-units: Unable to get repository
[INFO]  --> Fetching github.com/magiconair/properties.
[WARN]  Unable to checkout github.com/fatih/color
[ERROR] Update failed for github.com/fatih/color: Unable to get repository
[INFO]  --> Fetching github.com/mattn/go-colorable.
[WARN]  Unable to checkout github.com/davecgh/go-spew
[ERROR] Update failed for github.com/davecgh/go-spew: Unable to get repository
[INFO]  --> Fetching github.com/mattn/go-isatty.
[WARN]  Unable to checkout github.com/fsnotify/fsnotify
[ERROR] Update failed for github.com/fsnotify/fsnotify: Unable to get repository
[INFO]  --> Fetching github.com/Microsoft/go-winio.
[WARN]  Unable to checkout github.com/inconshreveable/mousetrap
[ERROR] Update failed for github.com/inconshreveable/mousetrap: Unable to get repository
[INFO]  --> Fetching github.com/mitchellh/go-homedir.
[WARN]  Unable to checkout github.com/kr/fs
[ERROR] Update failed for github.com/kr/fs: Unable to get repository
[INFO]  --> Fetching github.com/mitchellh/mapstructure.
[WARN]  Unable to checkout github.com/klauspost/crc32
[ERROR] Update failed for github.com/klauspost/crc32: Unable to get repository
[INFO]  --> Fetching github.com/nats-io/go-nats-streaming.
[WARN]  Unable to checkout github.com/mattn/go-isatty
[ERROR] Update failed for github.com/mattn/go-isatty: Unable to get repository
[INFO]  --> Fetching github.com/nats-io/nats.
[WARN]  Unable to checkout github.com/magiconair/properties
[ERROR] Update failed for github.com/magiconair/properties: Unable to get repository
[INFO]  --> Fetching github.com/nats-io/nuid.
[WARN]  Unable to checkout github.com/hashicorp/hcl
[ERROR] Update failed for github.com/hashicorp/hcl: Unable to get repository
[INFO]  --> Fetching github.com/opencontainers/runc.
[WARN]  Unable to checkout github.com/howeyc/gopass
[ERROR] Update failed for github.com/howeyc/gopass: Unable to get repository
[INFO]  --> Fetching github.com/pelletier/go-buffruneio.
[WARN]  Unable to checkout github.com/cloudfoundry-incubator/candiedyaml
[ERROR] Update failed for github.com/cloudfoundry-incubator/candiedyaml: Unable to get repository
[INFO]  --> Fetching github.com/pelletier/go-toml.
[WARN]  Unable to checkout github.com/Microsoft/go-winio
[ERROR] Update failed for github.com/Microsoft/go-winio: Unable to get repository
[INFO]  --> Fetching github.com/pkg/errors.
[WARN]  Unable to checkout github.com/mitchellh/go-homedir
[ERROR] Update failed for github.com/mitchellh/go-homedir: Unable to get repository
[INFO]  --> Fetching github.com/pkg/sftp.
[WARN]  Unable to checkout github.com/mitchellh/mapstructure
[ERROR] Update failed for github.com/mitchellh/mapstructure: Unable to get repository
[INFO]  --> Fetching github.com/Shopify/sarama.
[WARN]  Unable to checkout github.com/mattn/go-colorable
[ERROR] Update failed for github.com/mattn/go-colorable: Unable to get repository
[INFO]  --> Fetching github.com/Sirupsen/logrus.
[WARN]  Unable to checkout github.com/nats-io/nuid
[ERROR] Update failed for github.com/nats-io/nuid: Unable to get repository
[INFO]  --> Fetching github.com/spf13/afero.
[WARN]  Unable to checkout github.com/pelletier/go-buffruneio
[ERROR] Update failed for github.com/pelletier/go-buffruneio: Unable to get repository
[INFO]  --> Fetching github.com/spf13/cast.
[WARN]  Unable to checkout github.com/golang/protobuf
[ERROR] Update failed for github.com/golang/protobuf: Unable to get repository
[INFO]  --> Fetching github.com/spf13/cobra.
[WARN]  Unable to checkout github.com/pkg/errors
[ERROR] Update failed for github.com/pkg/errors: Unable to get repository
[INFO]  --> Fetching github.com/spf13/jwalterweatherman.
[WARN]  Unable to checkout github.com/docker/go-connections
[ERROR] Update failed for github.com/docker/go-connections: Unable to get repository
[INFO]  --> Fetching github.com/spf13/pflag.
[WARN]  Unable to checkout github.com/grpc-ecosystem/grpc-gateway
[ERROR] Update failed for github.com/grpc-ecosystem/grpc-gateway: Unable to get repository
[INFO]  --> Fetching github.com/spf13/viper.
[WARN]  Unable to checkout github.com/pelletier/go-toml
[ERROR] Update failed for github.com/pelletier/go-toml: Unable to get repository
[INFO]  --> Fetching golang.org/x/crypto.
[WARN]  Unable to checkout github.com/nats-io/nats
[ERROR] Update failed for github.com/nats-io/nats: Unable to get repository
[INFO]  --> Fetching golang.org/x/net.
[WARN]  Unable to checkout github.com/google/go-github
[ERROR] Update failed for github.com/google/go-github: Unable to get repository
[INFO]  --> Fetching golang.org/x/oauth2.
[WARN]  Unable to checkout github.com/spf13/cast
[ERROR] Update failed for github.com/spf13/cast: Unable to get repository
[INFO]  --> Fetching golang.org/x/sys.
[WARN]  Unable to checkout github.com/Sirupsen/logrus
[ERROR] Update failed for github.com/Sirupsen/logrus: Unable to get repository
[INFO]  --> Fetching golang.org/x/text.
[WARN]  Unable to checkout github.com/spf13/afero
[ERROR] Update failed for github.com/spf13/afero: Unable to get repository
[INFO]  --> Fetching google.golang.org/appengine.
[WARN]  Unable to checkout golang.org/x/oauth2
[ERROR] Update failed for golang.org/x/oauth2: Unable to get repository
[INFO]  --> Fetching google.golang.org/grpc.
[WARN]  Unable to checkout golang.org/x/crypto
[ERROR] Update failed for golang.org/x/crypto: Unable to get repository
[INFO]  --> Fetching gopkg.in/olivere/elastic.v3.
[WARN]  Unable to checkout github.com/docker/engine-api
[ERROR] Update failed for github.com/docker/engine-api: Unable to get repository
[INFO]  --> Fetching gopkg.in/yaml.v2.
[WARN]  Unable to checkout github.com/spf13/cobra
[ERROR] Update failed for github.com/spf13/cobra: Unable to get repository
[WARN]  Unable to checkout github.com/pkg/sftp
[ERROR] Update failed for github.com/pkg/sftp: Unable to get repository
[WARN]  Unable to checkout github.com/nats-io/go-nats-streaming
[ERROR] Update failed for github.com/nats-io/go-nats-streaming: Unable to get repository
[WARN]  Unable to checkout github.com/spf13/jwalterweatherman
[ERROR] Update failed for github.com/spf13/jwalterweatherman: Unable to get repository
[WARN]  Unable to checkout golang.org/x/sys
[ERROR] Update failed for golang.org/x/sys: Unable to get repository
[WARN]  Unable to checkout golang.org/x/net
[ERROR] Update failed for golang.org/x/net: Unable to get repository
[WARN]  Unable to checkout github.com/Shopify/sarama
[ERROR] Update failed for github.com/Shopify/sarama: Unable to get repository
[WARN]  Unable to checkout github.com/spf13/viper
[ERROR] Update failed for github.com/spf13/viper: Unable to get repository
[WARN]  Unable to checkout github.com/spf13/pflag
[ERROR] Update failed for github.com/spf13/pflag: Unable to get repository
[WARN]  Unable to checkout google.golang.org/appengine
[ERROR] Update failed for google.golang.org/appengine: Unable to get repository
[WARN]  Unable to checkout golang.org/x/text
[ERROR] Update failed for golang.org/x/text: Unable to get repository
[WARN]  Unable to checkout google.golang.org/grpc
[ERROR] Update failed for google.golang.org/grpc: Unable to get repository
[WARN]  Unable to checkout gopkg.in/yaml.v2
[ERROR] Update failed for gopkg.in/yaml.v2: Unable to get repository
[WARN]  Unable to checkout gopkg.in/olivere/elastic.v3
[ERROR] Update failed for gopkg.in/olivere/elastic.v3: Unable to get repository
[WARN]  Unable to checkout github.com/golang/snappy
[ERROR] Update failed for github.com/golang/snappy: Unable to get repository
[WARN]  Unable to checkout github.com/opencontainers/runc
[ERROR] Update failed for github.com/opencontainers/runc: Unable to get repository
[WARN]  Unable to checkout github.com/docker/distribution
[ERROR] Update failed for github.com/docker/distribution: Unable to get repository
[WARN]  Unable to checkout github.com/gogo/protobuf
[ERROR] Update failed for github.com/gogo/protobuf: Unable to get repository
[WARN]  Unable to checkout github.com/coreos/etcd
[ERROR] Update failed for github.com/coreos/etcd: Unable to get repository
[WARN]  Unable to checkout github.com/influxdata/influxdb
[ERROR] Update failed for github.com/influxdata/influxdb: Unable to get repository
[ERROR] Failed to install: Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Unable to get repository
Makefile:74: recipe for target 'install-deps' failed
make: *** [install-deps] Error 1
```

**Comment by subfuzion** [comment]
@bertrand-quenin It usually fails like that when the cache hasn't been deleted. Are you sure you deleted all the directories mentioned in the first step? I'd like to get to the bottom of this and identify if there is some other issue affecting you. Can we get everyone on the team to try?

**Comment by subfuzion** [comment]
@bertrand-quenin @freignat91 @ndegory @chrisccoy I added the ability to add a debug option when running make to install dependencies in #130:

```
$ GLIDE_OPTS=--debug make install-deps
```

Please try that if it doesn't work for you the first time. Note: installing with the debug option is very slow.

**Comment by subfuzion** [comment]
I've identified the issue:

```
$ GLIDE_OPTS=--debug make install-deps
. . .
fatal: unable to look up current user in the passwd file: no such user
. . .
```

I think I understand the problem, which is why I had closed my own PR on a previous attempt when I noted this: https://github.com/appcelerator/amp/pull/128#issuecomment-244515274. But the crazy thing is when I tried it again (on Docker for Mac) it worked, and subsequently also worked for @chrisccoy (on Linux) who merged this with: #131.

We're going to have to reopen the related issue, but probably table the attempt to containerized glide for now.

**Please simply confirm that the following steps work instead:**

```
$ rm -rf ~/.glide .glide vendor
$ glide install
$ make install
```

**Comment by bquenin** [comment]
Tested and working with:

```
$ rm -rf ~/.glide .glide vendor
$ glide install
$ make install
```

**Comment by freignat91** [comment]
tested ok with
$ rm -rf ~/.glide .glide vendor
$ glide install
$ make instal

**Pull request merged**
