### PR TITLE
Revert nats on telegraf

### PR DESCRIPTION
**Pull request by ndegory**
Temporary workaround for #141 
reverts commits ff580277a281fff7a82557eb634cfcd81ae71d8b d7531cc9ddd1fe90b65086b4cceab55d66cc5606 and 662bb9758d130115657c3994444329693598adb0
to bring back zookeeper and kafka for telemetry.
also fix the test-storage test command in the Makefile

### CODE REVIEW

**Comment by freignat91** [comment]
Tested ok, but remove the :nats tags in the IMAGES fichiers swarm

**Comment by ndegory** [comment]
@bertrand-quenin you commented the kafka advertising, won't it break amplifier?

**Comment by bquenin** [comment]
@ndegory the kafka workaround was required for logs streaming, but we're using nats now.

**Comment by freignat91** [comment]
Tested ok with Bertrand and Nicolas updates

**Comment by subfuzion** [comment]
@bertrand-quenin @freignat91 Reverted just a bit too quickly in my opinion. I would first test NATS Streaming with write acknowledgements enabled to compare it to Kafka's at-least-once delivery messaging semantics.

**Pull request merged**
