### PR TITLE
add telegraf service and grafana dashboard for haproxy stats

### PR DESCRIPTION
**Pull request by ndegory**
Warning: https://github.com/appcelerator/docker-haproxy/pull/2 (stats listener updates for haproxy:1.0.1) should be merged before this one.
- new telegraf-haproxy service, gathering stats from the haproxy service
- new Grafana dashboard for Haproxy stats

How to test:
$ swarm pull
$ swarm start
$ swarm monitor
once all services are up, connect to grafana (localhost:6001), authenticate with the admin login, and check the Load Balancer dashboard, data should be displayed.

### CODE REVIEW

**Review by generalhenry — APPROVED** [review]
Tested locally

**Review by freignat91 — APPROVED** [review]
LGTM
HAProxy is up to date on its branch 1.0.1 included stats listener updates

**Comment by subfuzion** [comment]
@ndegory Please rebase against master since we've made other swarm dependency changes (eg, zookeeper+kafka -> nats). Thanks!

**Review by freignat91 — APPROVED** [review]
LGTM

**Comment by ndegory** [comment]
was rebased, but tests are still failing. My tests are also failing on the master branch, so I can't confirm or disprove tests on this branch.

**Comment by subfuzion** [comment]
👍

**Pull request merged**
