### PR TITLE
remove docker vendor trace on install/update deps

### LINKED ISSUE #554: runtime panic due to trace
`amp` and `amplifier` panic after a fresh `glide install` and build. This is due to two initializations of trace both registering a listener for `/debug/trace`. The panic also occurs and prevents `amplifier` from starting up as a container when running `amp pf start`.

The current fix is to manually remove the vendored copy of trace:

    $ rm -rf vendor/github.com/docker/docker/vendor/golang.org/x/net/trace

We need to investigate possible solutions or else at the very least handle this as part of the Makefile `install-deps` rule.

### PR DESCRIPTION
**Pull request by generalhenry**
closes https://github.com/appcelerator/amp/issues/554

To test:

`rm -rf vendor`
`make install-deps`
`make install`
`amp`

### CODE REVIEW

**Comment by neha-viswanathan** [comment]
`make install-deps` fails to execute when updating vendor packages.

```
[INFO]  --> Fetching github.com/influxdata/influxdb.
[WARN]  Unable to checkout github.com/howeyc/gopass
[ERROR] Update failed for github.com/howeyc/gopass: Unable to get repository
[INFO]  --> Fetching github.com/magiconair/properties.
[WARN]  Unable to checkout github.com/docker/go-units
[ERROR] Update failed for github.com/docker/go-units: Unable to get repository
[INFO]  --> Fetching github.com/mattn/go-colorable.
[WARN]  Unable to checkout github.com/beorn7/perks
[ERROR] Update failed for github.com/beorn7/perks: Unable to get repository
[INFO]  --> Fetching github.com/mattn/go-isatty.
[WARN]  Unable to checkout github.com/google/go-querystring
[ERROR] Update failed for github.com/google/go-querystring: Unable to get repository
```

**Comment by generalhenry** [comment]
@neha-viswanathan that's docker acting up.

**Review by ndegory — DISMISSED** [review]
LGTM

**Comment by subfuzion** [comment]
Thanks, @generalhenry. Can you please include an update to the docs with this PR? [This section](https://github.com/appcelerator/amp/blob/master/docs/contributing.md#user-content-package-management) should be updated to recommend against using `glide install/update` directly and use the install/update rules described in the previous section.

**Review by bquenin — CHANGES_REQUESTED** [review]
Unfortunately, it probably works on OS X but it doesn't on linux. Here is the error I get:
```
$ rm -rf vendor
$ make install-deps
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching github.com/coreos/etcd.
[INFO]  --> Fetching github.com/docker/docker.
[INFO]  --> Fetching github.com/docker/go-connections.
[INFO]  --> Fetching github.com/fatih/structs.
[INFO]  --> Fetching github.com/fsnotify/fsnotify.
[INFO]  --> Fetching github.com/golang/protobuf.
[INFO]  --> Fetching github.com/fatih/color.
[INFO]  --> Fetching github.com/gogo/protobuf.
[INFO]  --> Fetching github.com/google/go-github.
[INFO]  --> Fetching github.com/ghodss/yaml.
[INFO]  --> Fetching github.com/google/go-querystring.
[INFO]  --> Fetching github.com/grpc-ecosystem/go-grpc-prometheus.
[INFO]  --> Fetching github.com/grpc-ecosystem/grpc-gateway.
[INFO]  --> Fetching github.com/hashicorp/hcl.
[INFO]  --> Fetching github.com/beorn7/perks.
[INFO]  --> Fetching github.com/docker/go-units.
[INFO]  --> Fetching github.com/docker/distribution.
[INFO]  --> Fetching github.com/inconshreveable/mousetrap.
[INFO]  --> Fetching github.com/influxdata/influxdb.
[INFO]  --> Fetching github.com/howeyc/gopass.
[WARN]  Unable to checkout github.com/ghodss/yaml
[ERROR] Update failed for github.com/ghodss/yaml: Unable to get repository
[INFO]  --> Fetching github.com/magiconair/properties.
[WARN]  Unable to checkout github.com/inconshreveable/mousetrap
[ERROR] Update failed for github.com/inconshreveable/mousetrap: Unable to get repository
[INFO]  --> Fetching github.com/mattn/go-colorable.
[WARN]  Unable to checkout github.com/howeyc/gopass
[ERROR] Update failed for github.com/howeyc/gopass: Unable to get repository
[INFO]  --> Fetching github.com/mattn/go-isatty.
[WARN]  Unable to checkout github.com/beorn7/perks
[ERROR] Update failed for github.com/beorn7/perks: Unable to get repository
[INFO]  --> Fetching github.com/matttproud/golang_protobuf_extensions.
...
```

When running glide with the `--debug` flag, I get this:
```
$ make install-deps
[DEBUG]	No mirrors.yaml file exists
[INFO]	Downloading dependencies. Please wait...
[DEBUG]	Setting up the cache directory
[DEBUG]	Locking https-github.com-grpc-ecosystem-grpc-gateway
[DEBUG]	Locking https-github.com-howeyc-gopass
[INFO]	--> Fetching github.com/grpc-ecosystem/grpc-gateway.
[INFO]	--> Fetching github.com/howeyc/gopass.
[DEBUG]	Locking https-github.com-fatih-structs
[DEBUG]	Adding github.com/grpc-ecosystem/grpc-gateway to the cache for the first time
[INFO]	--> Fetching github.com/fatih/structs.
[DEBUG]	Locking https-github.com-fatih-color
[INFO]	--> Fetching github.com/fatih/color.
[DEBUG]	Adding github.com/fatih/structs to the cache for the first time
[DEBUG]	Locking https-github.com-hashicorp-hcl
[DEBUG]	Adding github.com/fatih/color to the cache for the first time
[DEBUG]	Locking https-github.com-beorn7-perks
[INFO]	--> Fetching github.com/hashicorp/hcl.
[DEBUG]	Adding github.com/hashicorp/hcl to the cache for the first time
[INFO]	--> Fetching github.com/beorn7/perks.
[DEBUG]	Locking https-github.com-docker-go-connections
[DEBUG]	Adding github.com/beorn7/perks to the cache for the first time
[INFO]	--> Fetching github.com/docker/go-connections.
[DEBUG]	Locking https-github.com-golang-protobuf
[INFO]	--> Fetching github.com/golang/protobuf.
[DEBUG]	Adding github.com/golang/protobuf to the cache for the first time
[DEBUG]	Adding github.com/docker/go-connections to the cache for the first time
[DEBUG]	Locking https-github.com-gogo-protobuf
[INFO]	--> Fetching github.com/gogo/protobuf.
[DEBUG]	Adding github.com/gogo/protobuf to the cache for the first time
[DEBUG]	Locking https-github.com-google-go-querystring
[DEBUG]	Locking https-github.com-grpc-ecosystem-go-grpc-prometheus
[INFO]	--> Fetching github.com/google/go-querystring.
[DEBUG]	Locking https-github.com-influxdata-influxdb
[INFO]	--> Fetching updates for github.com/influxdata/influxdb.
[DEBUG]	Locking https-github.com-inconshreveable-mousetrap
[DEBUG]	Locking https-github.com-docker-docker
[DEBUG]	Adding github.com/google/go-querystring to the cache for the first time
[INFO]	--> Fetching github.com/docker/docker.
[DEBUG]	Adding github.com/docker/docker to the cache for the first time
[DEBUG]	Locking https-github.com-ghodss-yaml
[INFO]	--> Fetching github.com/ghodss/yaml.
[DEBUG]	Adding github.com/ghodss/yaml to the cache for the first time
[DEBUG]	Locking https-github.com-fsnotify-fsnotify
[INFO]	--> Fetching github.com/fsnotify/fsnotify.
[DEBUG]	Adding github.com/fsnotify/fsnotify to the cache for the first time
[DEBUG]	Locking https-github.com-docker-go-units
[INFO]	--> Fetching github.com/docker/go-units.
[DEBUG]	Adding github.com/docker/go-units to the cache for the first time
[DEBUG]	Locking https-github.com-google-go-github
[INFO]	--> Fetching github.com/google/go-github.
[DEBUG]	Locking https-github.com-coreos-etcd
[INFO]	--> Fetching github.com/coreos/etcd.
[DEBUG]	Adding github.com/google/go-github to the cache for the first time
[DEBUG]	Adding github.com/coreos/etcd to the cache for the first time
[DEBUG]	Locking https-github.com-docker-distribution
[INFO]	--> Fetching github.com/docker/distribution.
[DEBUG]	Adding github.com/docker/distribution to the cache for the first time
[INFO]	--> Fetching github.com/inconshreveable/mousetrap.
[DEBUG]	Adding github.com/inconshreveable/mousetrap to the cache for the first time
[DEBUG]	Adding github.com/howeyc/gopass to the cache for the first time
[INFO]	--> Fetching github.com/grpc-ecosystem/go-grpc-prometheus.
[DEBUG]	Adding github.com/grpc-ecosystem/go-grpc-prometheus to the cache for the first time
[ERROR]	Update failed for github.com/influxdata/influxdb: Unable to retrieve checked out version
[DEBUG]	Output was: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
HEAD[DEBUG]	Unlocking https-github.com-influxdata-influxdb
[DEBUG]	Locking https-github.com-magiconair-properties
[INFO]	--> Fetching github.com/magiconair/properties.
[DEBUG]	Adding github.com/magiconair/properties to the cache for the first time
[WARN]	Unable to checkout github.com/google/go-querystring
[ERROR]	Update failed for github.com/google/go-querystring: Unable to get repository
[DEBUG]	Output was: Cloning into '/go/src/github.com/appcelerator/amp/.glide/cache/src/https-github.com-google-go-querystring'...
fatal: You don't exist. Go away!
Unexpected end of command stream[DEBUG]	Unlocking https-github.com-google-go-querystring
[DEBUG]	Locking https-github.com-mattn-go-colorable
[INFO]	--> Fetching github.com/mattn/go-colorable.
[DEBUG]	Adding github.com/mattn/go-colorable to the cache for the first time
[WARN]	Unable to checkout github.com/ghodss/yaml
[ERROR]	Update failed for github.com/ghodss/yaml: Unable to get repository
[DEBUG]	Output was: Cloning into '/go/src/github.com/appcelerator/amp/.glide/cache/src/https-github.com-ghodss-yaml'...
fatal: You don't exist. Go away!
Unexpected end of command stream[DEBUG]	Unlocking https-github.com-ghodss-yaml
[DEBUG]	Locking https-github.com-mattn-go-isatty
[INFO]	--> Fetching github.com/mattn/go-isatty.
[DEBUG]	Adding github.com/mattn/go-isatty to the cache for the first time
[WARN]	Unable to checkout github.com/inconshreveable/mousetrap
[ERROR]	Update failed for github.com/inconshreveable/mousetrap: Unable to get repository
[DEBUG]	Output was: Cloning into '/go/src/github.com/appcelerator/amp/.glide/cache/src/https-github.com-inconshreveable-mousetrap'...
fatal: You don't exist. Go away!
Unexpected end of command stream[DEBUG]	Unlocking https-github.com-inconshreveable-mousetrap
[DEBUG]	Locking https-github.com-matttproud-golang_protobuf_extensions
[INFO]	--> Fetching github.com/matttproud/golang_protobuf_extensions.
[DEBUG]	Adding github.com/matttproud/golang_protobuf_extensions to the cache for the first time
...
```

The recurring message `fatal: You don't exist. Go away!` comes from git. I tried to resolve it by adding the `.gitconfig` to the home folder of the user like this:
```
GLIDE := $(DOCKER_RUN) -u $(UG) -v $$HOME:$$HOME -e HOME=$$HOME -v $${PWD}:/go/src/$(REPO) -w /go/src/$(REPO) $(GOTOOLS) glide $${GLIDE_OPTS}
```
Then I got the following error:
```
make install-deps
[DEBUG]	No mirrors.yaml file exists
[INFO]	Downloading dependencies. Please wait...
[DEBUG]	Setting up the cache directory
[DEBUG]	Locking https-github.com-coreos-etcd
[DEBUG]	Locking https-github.com-beorn7-perks
[DEBUG]	Locking https-github.com-docker-go-connections
[DEBUG]	Locking https-github.com-docker-docker
[INFO]	--> Fetching github.com/docker/go-connections.
[DEBUG]	Locking https-github.com-docker-go-units
[DEBUG]	Locking https-github.com-golang-protobuf
[INFO]	--> Fetching github.com/coreos/etcd.
[DEBUG]	Locking https-github.com-google-go-github
[INFO]	--> Fetching github.com/docker/go-units.
[INFO]	--> Fetching github.com/golang/protobuf.
[INFO]	--> Fetching github.com/google/go-github.
[DEBUG]	Adding github.com/docker/go-connections to the cache for the first time
[DEBUG]	Adding github.com/coreos/etcd to the cache for the first time
[DEBUG]	Adding github.com/golang/protobuf to the cache for the first time
[INFO]	--> Fetching github.com/beorn7/perks.
[DEBUG]	Locking https-github.com-grpc-ecosystem-grpc-gateway
[INFO]	--> Fetching github.com/grpc-ecosystem/grpc-gateway.
[DEBUG]	Adding github.com/beorn7/perks to the cache for the first time
[DEBUG]	Locking https-github.com-howeyc-gopass
[DEBUG]	Locking https-github.com-hashicorp-hcl
[DEBUG]	Locking https-github.com-fatih-color
[DEBUG]	Locking https-github.com-inconshreveable-mousetrap
[DEBUG]	Locking https-github.com-influxdata-influxdb
[DEBUG]	Locking https-github.com-gogo-protobuf
[DEBUG]	Adding github.com/google/go-github to the cache for the first time
[DEBUG]	Locking https-github.com-google-go-querystring
[INFO]	--> Fetching github.com/google/go-querystring.
[DEBUG]	Locking https-github.com-ghodss-yaml
[INFO]	--> Fetching github.com/ghodss/yaml.
[DEBUG]	Adding github.com/google/go-querystring to the cache for the first time
[DEBUG]	Locking https-github.com-fsnotify-fsnotify
[DEBUG]	Adding github.com/grpc-ecosystem/grpc-gateway to the cache for the first time
[INFO]	--> Fetching github.com/fsnotify/fsnotify.
[DEBUG]	Adding github.com/fsnotify/fsnotify to the cache for the first time
[INFO]	--> Fetching github.com/fatih/color.
[DEBUG]	Adding github.com/docker/go-units to the cache for the first time
[INFO]	--> Fetching github.com/hashicorp/hcl.
[INFO]	--> Fetching github.com/howeyc/gopass.
[INFO]	--> Fetching github.com/docker/docker.
[WARN]	Unable to checkout github.com/golang/protobuf
[ERROR]	Update failed for github.com/golang/protobuf: Unable to get repository
[DEBUG]	Output was: error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 6 in /home/bq/.gitconfig
Cloning into '/go/src/github.com/appcelerator/amp/.glide/cache/src/https-github.com-golang-protobuf'...[DEBUG]	Unlocking https-github.com-golang-protobuf
[DEBUG]	Adding github.com/docker/docker to the cache for the first time
[DEBUG]	Locking https-github.com-magiconair-properties
```

Note the:
```
error: Malformed value for push.default: simple
error: Must be one of nothing, matching, tracking or current.
fatal: bad config file line 6 in /home/bq/.gitconfig
```

After checking, it's because `appcelerator/gotools2:1.0.0` image uses git version 1.7.10.4, which is pretty outdated. For reference, I'm running git version 2.7.4 on my laptop.

Even after "fixing" my `.gitconfig`, I still got an error:
```
make install-deps
[DEBUG]	No mirrors.yaml file exists
[INFO]	Downloading dependencies. Please wait...
[DEBUG]	Setting up the cache directory
[INFO]	--> Found desired version locally github.com/beorn7/perks 4c0e84591b9aa9e6dcfdf3e020114cd81f89d5f9!
[INFO]	--> Found desired version locally github.com/coreos/etcd 3d5ba43211beec7fbb1472634a9c3b464581658a!
[INFO]	--> Found desired version locally github.com/docker/distribution c59995570762ec8ef1b1d5a0b147600622979cb1!
[INFO]	--> Found desired version locally github.com/docker/docker 005a5428ee1b3f7f2efca2d761f27bd168356fa1!
[INFO]	--> Found desired version locally github.com/docker/go-connections 4ccf312bf1d35e5dbda654e57a9be4c3f3cd0366!
[INFO]	--> Found desired version locally github.com/docker/go-units e30f1e79f3cd72542f2026ceec18d3bd67ab859c!
[INFO]	--> Found desired version locally github.com/fatih/color dea9d3a26a087187530244679c1cfb3a42937794!
[INFO]	--> Found desired version locally github.com/fatih/structs dc3312cb1a4513a366c4c9e622ad55c32df12ed3!
[INFO]	--> Found desired version locally github.com/fsnotify/fsnotify fd9ec7deca8bf46ecd2a795baaacf2b3a9be1197!
[INFO]	--> Found desired version locally github.com/ghodss/yaml 73d445a93680fa1a78ae23a5839bad48f32ba1ee!
[INFO]	--> Found desired version locally github.com/golang/protobuf 8616e8ee5e20a1704615e6c8d7afcdac06087a67!
[INFO]	--> Found desired version locally github.com/google/go-github 4e2c2aeb92b9a57d97165d1624ff66b2aabee111!
[INFO]	--> Found desired version locally github.com/google/go-querystring 9235644dd9e52eeae6fa48efd539fdc351a0af53!
[INFO]	--> Found desired version locally github.com/grpc-ecosystem/go-grpc-prometheus 6b7015e65d366bf3f19b2b2a000a831940f0f7e0!
[INFO]	--> Found desired version locally github.com/grpc-ecosystem/grpc-gateway a8f25bd1ab549f8b87afd48aa9181221e9d439bb!
[INFO]	--> Found desired version locally github.com/hashicorp/hcl ae25c981c128d7a7a5241e3b7d7409089355df69!
[INFO]	--> Found desired version locally github.com/howeyc/gopass f5387c492211eb133053880d23dfae62aa14123d!
[INFO]	--> Found desired version locally github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75!
[INFO]	--> Found desired version locally github.com/magiconair/properties 9c47895dc1ce54302908ab8a43385d1f5df2c11c!
[INFO]	--> Found desired version locally github.com/mattn/go-colorable d228849504861217f796da67fae4f6e347643f15!
[INFO]	--> Found desired version locally github.com/mattn/go-isatty 30a891c33c7cde7b02a981314b4228ec99380cca!
[INFO]	--> Found desired version locally github.com/matttproud/golang_protobuf_extensions c12348ce28de40eed0136aa2b644d0ee0650e56c!
[INFO]	--> Found desired version locally github.com/Microsoft/go-winio 24a3e3d3fc7451805e09d11e11e95d9a0a4f205e!
[INFO]	--> Found desired version locally github.com/mitchellh/go-homedir 756f7b183b7ab78acdbbee5c7f392838ed459dda!
[INFO]	--> Found desired version locally github.com/mitchellh/mapstructure f3009df150dadf309fdee4a54ed65c124afad715!
[INFO]	--> Found desired version locally github.com/nats-io/go-nats-streaming f0b13ceaf55c6d86604169520dfd8ee3c03e9524!
[INFO]	--> Found desired version locally github.com/nats-io/nats 61923ed1eaf8398000991fbbee2ef11ab5a5be0d!
[INFO]	--> Found desired version locally github.com/nats-io/nuid 289cccf02c178dc782430d534e3c1f5b72af807f!
[INFO]	--> Found desired version locally github.com/opencontainers/runc 8893fa693bf9bf29e5a156369bc51b887df43924!
[INFO]	--> Found desired version locally github.com/pelletier/go-buffruneio df1e16fde7fc330a0ca68167c23bf7ed6ac31d6d!
[INFO]	--> Found desired version locally github.com/pelletier/go-toml 7cb988051d5045890cb91402a0b5fddc76c627bc!
[INFO]	--> Found desired version locally github.com/pkg/errors 248dadf4e9068a0b3e79f02ed0a610d935de5302!
[INFO]	--> Found desired version locally github.com/prometheus/client_golang e51041b3fa41cece0dca035740ba6411905be473!
[INFO]	--> Found desired version locally github.com/prometheus/client_model fa8ad6fec33561be4280a8f0514318c79d7f6cb6!
[INFO]	--> Found desired version locally github.com/prometheus/common 195bde7883f7c39ea62b0d92ab7359b5327065cb!
[INFO]	--> Found desired version locally github.com/prometheus/procfs abf152e5f3e97f2fafac028d2cc06c1feb87ffa5!
[INFO]	--> Found desired version locally github.com/Sirupsen/logrus 55eb11d21d2a31a3cc93838241d04800f52e823d!
[INFO]	--> Found desired version locally github.com/spf13/afero 06b7e5f50606ecd49148a01a6008942d9b669217!
[INFO]	--> Found desired version locally github.com/spf13/cast 24b6558033ffe202bf42f0f3b870dcc798dd2ba8!
[INFO]	--> Found desired version locally github.com/spf13/cobra 9495bc009a56819bdb0ddbc1a373e29c140bc674!
[INFO]	--> Found desired version locally github.com/spf13/jwalterweatherman 33c24e77fb80341fe7130ee7c594256ff08ccc46!
[INFO]	--> Found desired version locally github.com/spf13/pflag 5ccb023bc27df288a957c5e994cd44fd19619465!
[INFO]	--> Found desired version locally github.com/spf13/viper 651d9d916abc3c3d6a91a12549495caba5edffd2!
[INFO]	--> Found desired version locally golang.org/x/crypto 21853a76e0cca35cf785c34dceee499a3d5a7168!
[INFO]	--> Found desired version locally golang.org/x/net 6acef71eb69611914f7a30939ea9f6e194c78172!
[INFO]	--> Found desired version locally golang.org/x/oauth2 f6093e37b6cb4092101a298aba5d794eb570757f!
[INFO]	--> Found desired version locally golang.org/x/sys 9c60d1c508f5134d1ca726b4641db998f2523357!
[INFO]	--> Found desired version locally golang.org/x/text 5c6cf4f9a2357d38515014cea8c488ed22bdab90!
[INFO]	--> Found desired version locally google.golang.org/appengine 12d5545dc1cfa6047a286d5e853841b6471f4c19!
[INFO]	--> Found desired version locally google.golang.org/grpc 777daa17ff9b5daef1cfdf915088a2ada3332bf0!
[INFO]	--> Found desired version locally gopkg.in/olivere/elastic.v3 b272fab42387a42585235d56f8c6b53b13ddfb7d!
[INFO]	--> Found desired version locally gopkg.in/olivere/elastic.v5 0746557b3f90c3119b44e7d7ee0f76db3ff26acb!
[INFO]	--> Found desired version locally gopkg.in/yaml.v2 53feefa2559fb8dfa8d81baad31be332c97d6c77!
[DEBUG]	Locking https-github.com-gogo-protobuf
[DEBUG]	Locking https-github.com-influxdata-influxdb
[INFO]	--> Fetching updates for github.com/gogo/protobuf.
[INFO]	--> Fetching updates for github.com/influxdata/influxdb.
[ERROR]	Update failed for github.com/influxdata/influxdb: Unable to retrieve checked out version
[DEBUG]	Output was: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
HEAD[DEBUG]	Unlocking https-github.com-influxdata-influxdb
[ERROR]	Update failed for github.com/gogo/protobuf: Unable to retrieve checked out version
[DEBUG]	Output was: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
HEAD[DEBUG]	Unlocking https-github.com-gogo-protobuf
[ERROR]	Failed to install: Unable to retrieve checked out version
Unable to retrieve checked out version
Makefile:82: recipe for target 'install-deps' failed
make: *** [install-deps] Error 1
```

And I don't really know how to fix this one ...
Maybe using a more recent version of git in the `appcelerator/gotools2` image would help?

**Review by ndegory — CHANGES_REQUESTED** [review]
I was able to make it work with this change (different mount for the glide cache, and glide home option):
-GLIDE := $(DOCKER_RUN) -u $(UG) -v $${HOME}/.ssh:/root/.ssh -v $${HOME}/.glide:/root/.glide -v $${PWD}:/go/src/$(REPO) -w /go/src/$(REPO) $(GOTOOLS) glide $${GLIDE_OPTS}
+GLIDE := $(DOCKER_RUN) -u $(UG) -v $${HOME}/.ssh:/root/.ssh -v $${HOME}/.glide:/mnt/glide -v $${PWD}:/go/src/$(REPO) -w /go/src/$(REPO) $(GOTOOLS) glide --home /mnt/glide $${GLIDE_OPTS}

**Comment by bquenin** [comment]
Ok, I got it working (on linux), but we need the following changes:
 - Merge this PR (and probably tag): https://github.com/appcelerator/docker-gotools/pull/3
 - Use this glide statement `GLIDE := $(DOCKER_RUN) -e HOME=$$HOME -v $$HOME:$$HOME -e GLIDE_HOME=$$HOME/.glide -v $${PWD}:/go/src/$(REPO) -w /go/src/$(REPO) $(GOTOOLS) glide $${GLIDE_OPTS}`

**Review by bquenin — APPROVED** [review]

**Comment by bquenin** [comment]
Ok, I committed the changes on the branch. Can you please confirm it's still working on OS X?

**Comment by ndegory** [comment]
@bquenin , no, there's a regression on the gotools image, let's talk about it this morning...

**Review by ndegory — APPROVED** [review]

**Review by bquenin — APPROVED** [review]
LGTM, tested on linux

**Pull request merged**
