### PR TITLE
Travis Build Update for amp version

### PR DESCRIPTION
**Pull request by neha-viswanathan**
Related to #840 
Updated Travis Build to include `amp version`

### CODE REVIEW

**Review by subfuzion — APPROVED** [review]
Looks good for now until we refactor the smoke tests. Thanks!

**Comment by freignat91** [comment]
Needs some squash, no?

**Comment by subfuzion** [comment]
@freignat91 Yes, it does, but I told @neha-viswanathan I would take care of it after we finished debugging some of the networking issues. This is useful for us right now as an open PR for testing CI builds. I'll be rebasing the latest CI updates and testing, then removing the debugging code, and will squash and merge for her.

**Review by subfuzion — APPROVED** [review]
LGTM

**Pull request merged**
