### PR TITLE
Amplifier updates

### PR DESCRIPTION
**Pull request by subfuzion**
The PR leverages the new containerized toolchain:

```sh
$ ampmake build
```

To bootstrap the swarm, use the following command:

```sh
$ stacks/local-bootstrap
. . .
---------------------------------------------------------------------------
swarm running at 127.0.0.1:62001
---------------------------------------------------------------------------
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
gs2ehb4w3x0cd759dpwkt5cno    m2        Ready   Active        Reachable
k14m20l44gh0wfau4wy6tn491    w2        Ready   Active        
od7fas5v6utjef9oc59dtqpig    w1        Ready   Active        
qr9vvw494gfoxv9mv2mqztej6    m3        Ready   Active        Reachable
ymvb8h5rn2qct8l1pqg6xy1r9 *  m1        Ready   Active        Leader
```

You can provide additional options for creating the swarm manager, primarily for publishing any extra ports besides the default ones on the swarm that gets created (`80`, `8080`, `3000`, `50101`).

You can deploy the `amplifier` and `amp` images to the registry for the cluster:

```sh
# amplifier
$ docker tag appcelerator/amplifier:local 127.0.0.1:5000/appcelerator/amplifier:local
$ docker push 127.0.0.1:5000/appcelerator/amplifier:local

# amp cli
$ docker tag appcelerator/amp:local 127.0.0.1:5000/appcelerator/amp:local
$ docker push 127.0.0.1:5000/appcelerator/amp:local
```

You then deploy `amplifier` to the swarm with the following command:

    $ docker --host=127.0.0.1:62001 deploy -c stacks/amplifier.stack.yml amp

To connect the `amp` cli to to `amplifier`, enter the following with or without cli commands (note: only the `version` command works right now):

You can then start the `amp` cli inside the swarm:

    $  docker --host=127.0.0.1:62001 run -it --rm --name amp --network=ampnet appcelerator/amp:local --server=amplifier:50101

For example, the following command causes the cli to query `amplifier` for version information from the server:

    $  docker --host=127.0.0.1:62001 run -it --rm --name amp --network=ampnet appcelerator/amp:local --server=amplifier:50101 version

image

And you can connect to the swarm visualizer at `localhost:8080`:

image

### CODE REVIEW

**Comment by ndegory** [comment]
@subfuzion in case you're still looking for a solution, there's one way to make the images that were built on the host available on a DinD container:

### on the host
```
$ docker image ls appcelerator/amp
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
appcelerator/amp    latest              c0cf48313760        2 days ago          26.2 MB
[...]
$ docker image save appcelerator/amp:latest | gzip -c > /tmp/images/appcelerator_amp_latest.tgz
$ ls -lh /tmp/images/appcelerator_amp.tgz
-rw-r--r--  1 ndegory  staff   7.5M Feb  8 07:33 appcelerator_amp.tgz
```
### on the containers
each DinD container should mount /tmp/images (read only is enough)
```
# for image in $(ls /tmp/images/*.tgz); do gunzip -c $image | docker image load ; done
```

**Comment by subfuzion** [comment]
@ndegory That is very clever. I was thinking of just pushing to a registry running in the swarm, but I like your idea and will give it a shot. Thanks! 👍 

The thing that bothers me about the idea, however, is that it would be necessary to untar and load the image on each node individually. What I was saying to you the evening before is that since I've already got a registry service running that I've configured each node to use, I should just be able to push to that registry and then be able to use the images from any node. I want to give that a shot first before I try anything else.

**Comment by subfuzion** [comment]
@ndegory I've got good news! The original registry idea I had actually works:

    $ docker tag appcelerator/amplifier:local 127.0.0.1:5000/appcelerator/amplifier:local
    $ docker push 127.0.0.1:5000/appcelerator/amplifier:local

Same for the cli:

    $ docker tag appcelerator/amp:local 127.0.0.1:5000/appcelerator/amp:local
    $ docker push 127.0.0.1:5000/appcelerator/amp:local

Then the steps described in the PR description above succeed now! I'll demo this tomorrow. I'm pretty happy now.

I've updated the description with this now.

**Review by ndegory — APPROVED** [review]
LGTM, travis tests are failing but we'll have to migrate them in later PRs

**Pull request merged**
