### PR TITLE
[0.7.0] Vendor update for ampmail

### PR DESCRIPTION
**Pull request by freignat91**
#related to #748 

adding github.com/gorilla/mux
adding github.com/mhale/smtpd

### CODE REVIEW

**Review by ndegory — APPROVED** [review]
LGTM

**Review by JosephGJ — APPROVED** [review]
LGTM

**Comment by freignat91** [comment]
close it to move it on v0.7.0

**Comment by ndegory** [comment]
@freignat91 you don't have to close it, if you click on Edit on top of the page, you can change the branch you want to merge into.

**Pull request merged**
