### PR TITLE
[0.7.0] update amp configuration for ampmail

### PR DESCRIPTION
**Pull request by freignat91**
related to #755 

-make configuration loadable from outside amp/cmd
-add ampmail configuration setting

test:
amp config

### CODE REVIEW

**Review by JosephGJ — APPROVED** [review]
LGTM. Test should be `amp config`.

**Comment by freignat91** [comment]
@JosephGJ , yes, you're right, i updated it. Thanks

**Comment by freignat91** [comment]
close it to move it on v0.7.0

**Review by bquenin — APPROVED** [review]
LGTM. Tested on Linux.

**Pull request merged**
