### PR TITLE
Creating ~/registry/data folder in order to avoid log flooding

### PR DESCRIPTION
**Pull request by bquenin**
# Verification

```
$ rm -rf ~/registry/data
$ ./swarm start
```

Verify that the `~/registry/data` folder is created.

### CODE REVIEW

**Review by freignat91 — APPROVED** [review]
LGTM

**Comment by ndegory** [comment]
LNGTM

**Comment by ndegory** [comment]
the registry service is now using a named volume (#281), so no need of a mount point on the host

**Comment by bquenin** [comment]
Ok, reverting with #286

**Comment by subfuzion** [comment]
@bertrand-quenin @ndegory @freignat91 The title of this PR alone is not a good enough explanation of the problem nor why creating a directory helps. This is a good example of the kind of PR "rubber stamping" we want to avoid. We want to ensure that PRs will make sense to anyone else reviewing them.

**Pull request merged**
