### PR TITLE
Removing kibana

### PR DESCRIPTION
**Pull request by bquenin**
Removing kibana since it was there for debugging purposes. The preferred way to consult logs is the amp CLI or UI.

### CODE REVIEW

**Review by ndegory — APPROVED** [review]
LGTM

**Comment by ndegory** [comment]
@bertrand-quenin @freignat91 we'll need to remove kibana from the default conf of the haproxy service, or else it will fail to start:
[ALERT] 266/192047 (11) : parsing [/usr/local/etc/haproxy/haproxy.cfg:63] : 'server kibana1' : invalid address: 'kibana' in 'kibana:5601'

**Comment by bquenin** [comment]
Good catch!

**Comment by subfuzion** [comment]
@ndegory @bertrand-quenin I'll wait to merge until I hear that the related config entry [here](https://github.com/appcelerator/docker-haproxy/blob/master/haproxy.cfg.tpt#L23) has been made and pushed to the hub.

**Comment by freignat91** [comment]
Haproxy is up to date. Kibana has been removed

**Comment by subfuzion** [comment]
Thanks, @freignat91

**Comment by subfuzion** [comment]
@ndegory @freignat91 Doesn't look like the image has been updated yet. Last push was two days ago. Looks like there was an issue with automated builds; I'm working on resolving it now.

**Comment by subfuzion** [comment]
@freignat91 The builds fail because of vendoring. You used my makefile for this repo, but the vendoring support is out of date. I'll go ahead and fix.

**Comment by subfuzion** [comment]
@ndegory @freignat91 I've got [docker-haproxy](https://hub.docker.com/r/appcelerator/haproxy/builds/bukceyh8qzfbkd5yqybgclu/) building successfully again. Make sure to be using the latest version of glide when adding/updating vendor deps, since the older one didn't default to source only. I had to remove the cached submodules for automated builds to work.

**Pull request merged**
