### PR TITLE
Asynchronous execution of test specs

### PR DESCRIPTION
**Pull request by JosephGJ**
TestSpecs run in parallel. Uses a waitgroup to do so.

Minor change to service port range.

to test -
`go test ./tests/cli`

### CODE REVIEW

**Comment by bquenin** [comment]
I'm not sure it's a great idea to run tests in parallel, but maybe I missed something.

**Comment by generalhenry** [comment]
@bquenin reasons to parallel test:
1. It prevents our test time from creeping up too fast
2. It's a more realistic scenario since in production things moving in parallel is the norm

If it becomes an issue we can fall back to serial testing, or work on improving isolation (such as having a fresh amp stack per suite)

**Comment by subfuzion** [comment]
@bquenin It was a discussion that occurred at meetings in the Mountain View office and also in comments for several issues (such as [this](https://github.com/appcelerator/amp/issues/374#issuecomment-255879628)). However, that's not your fault for missing anything, it's my fault; these really should have been captured in the issue I opened around [testing](https://github.com/appcelerator/amp/issues/384), so I'll work on ensuring the thoughts and expectations previously discussed get captured in the parent issue.

The bottom line is that there generally is no expectation that tests run in a certain order, but we also wanted to provide support for explicit sequences. An ordered sequence can only happen within a test file when specified using yaml array syntax. Commands specified as array elements run in sequence, and the next command doesn't start until the previous command returns. Because the previous command may have started an asynchronous operation that won't actually complete until some time after the command itself returns, we're adding support for things like retrying API calls until a response indicates a success or failure status or else times out or exceeds the specified number of retries. Except for this, all other tests should be able to run with some configurable maximum degree of parallelism.

**Comment by subfuzion** [comment]
@JosephGJ Please reference the associated issue in your PR descriptions. Thanks.

**Comment by bquenin** [comment]
@generalhenry @subfuzion thanks for your feedback, it's more clear now. I was just concerned of side effects and particular care that we would need to write test but @generalhenry nailed it when he said **2. It's a more realistic scenario since in production things moving in parallel is the norm**

Acked.

**Comment by JosephGJ** [comment]
Update to asynchronous commands to work in combination with contexts.

Each context uses a goroutine of the `checkTimeout` method to continuously call the `.Done()` function in the contexts select statement. The goroutine fails the test if the deadline is exceeded. If cancelled, the test has passed.

to test
`go test ./tests/cli`

If you want to test some failing cases, insert some random values into the commands timeout field in the yaml file as a duration in string form.

**Review by generalhenry — APPROVED** [review]

**Pull request merged**
