### PR TITLE
Fix cloudfoundry/bytefmt vendoring

### PR DESCRIPTION
**Pull request by ndegory**
The cloudfoundry package was not using the recommended URL.

### CODE REVIEW

**Comment by bquenin** [comment]
Unfortunately, this doesn't work:
```
$ rm -rf Gopkg.lock vendor
$ dep ensure
ensure Solve(): No versions of github.com/grpc-ecosystem/go-grpc-middleware met constraints:
	master: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@master, as it has a dependency on google.golang.org/grpc with constraint ^1.8.0, which has no overlap with existing constraint 1.5.2 from (root)
	better_docs: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@better_docs, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	bugfix/37-panic-on-err: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@bugfix/37-panic-on-err, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	bugfix/extract_logging_suits: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@bugfix/extract_logging_suits, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	bugfix/logrus: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@bugfix/logrus, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	docs/improv: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@docs/improv, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	docs_examples: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@docs_examples, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/auth_and_backoff: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/auth_and_backoff, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/auth_middleware: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/auth_middleware, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/clieant-stream-chain: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/clieant-stream-chain, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/client-streaming-chain: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/client-streaming-chain, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/client-unary-chain: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/client-unary-chain, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/client_logging: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/client_logging, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/client_payload_logging: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/client_payload_logging, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/client_retry: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/client_retry, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/generic-loggign: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/generic-loggign, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/logging_zap: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/logging_zap, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/metadata_helpers: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/metadata_helpers, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/new_nicemd: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/new_nicemd, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/opentracing-both: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/opentracing-both, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/opentracing_tags: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/opentracing_tags, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/repo-move: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/repo-move, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/tags: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/tags, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	feature/validator-middlewre: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@feature/validator-middlewre, as it is not allowed by constraint master from project github.com/appcelerator/amp.
	goimports-scripts: Could not introduce github.com/grpc-ecosystem/go-grpc-middleware@goimports-scripts, as it is not allowed by constraint master from project github.com/appcelerator/amp. 
```

**Comment by ndegory** [comment]
Not fixing AMP-98, but nonetheless required to fixes the vendoring for bytefmt.

**Comment by bquenin** [comment]
#1778 Fixes all vendor issues, including this one

**Comment by ndegory** [comment]
cool, so closing this one.

**Pull request closed without merging**
