### PR TITLE
switch back to etcd 3.1

### LINKED ISSUE #377: etcd failing to start
appcelerator/etcd:3.1 (based on [etcd v3.1.0-rc.0](https://github.com/coreos/etcd/tree/v3.1.0-rc.0)) fails to start. Rolling back to 3.0 fixes. The swarm script should specify `3.0` until `3.1` is verified to work.

### PR DESCRIPTION
**Pull request by ndegory**
Fix #377

appcelerator/etcd:3.1 image has been rebuild with a more robust healthcheck command.

To be tested on Docker for Mac where the first 3.1 images of etcd were failing their healthchecks.

How to test:
- swarm start
- make test

### CODE REVIEW

**Comment by ndegory** [comment]
tests are passing on my Docker 1.12.2 / Ubuntu

**Review by freignat91 — APPROVED** [review]
Tested ok on ubuntu and mac

**Comment by subfuzion** [comment]
What changed? Can you provide a link to the fix? I don't see any commits to the [etcd repo](https://github.com/appcelerator/docker-etcd/commits/master) itself. Whatever you have done, now even Grafana starts for me, and log tests are finally passing as well. 👍

**Comment by ndegory** [comment]
it's in branch appcelerator/etcd:3.1, two last commits:
08ba08f9c3e15831eca9912682d3394d20e07e68
3aee7bb33a1b1323fde1fb418cd2fa57f8bdbf82

**Comment by subfuzion** [comment]
Ah, right, the `3.1` branch. Thanks. The crazy thing is suddenly everything else that was problematic for the past week or so is also working now. Knock on wood...

**Pull request merged**
