### PR TITLE
Bootstrap commands

### PR DESCRIPTION
**Pull request by ndegory**
# Content

Ref #839 

- cluster sizing through worker and manager counts
- force start option
- Cluster label

# Verification

This verification doesn't use the AMP CLI because it's not ready yet.
```
./bootstrap/bootstrap -m 3 -w 2 -l test
./hack/nodecheck 5 30 Cluster=test
./bootstrap/bootstrap -c
```

# Limitations

Right now the manager count is ignored (defaults to 3). It will be implemented in a subsequent PR

### CODE REVIEW

**Comment by neha-viswanathan** [comment]
Tried using the force start option, got an error response.
```
$ ./bootstrap/bootstrap -f
preparing a Docker image with the configuration data
warning: force start, removing Docker volume amp-bootstrap
Error response from daemon: unable to remove volume: remove amp-bootstrap: volume is in use - [2b7fa2847fb68b7aca5b522f8b566323ca942a0495274f188d6079cfd58e8247, 78a3168d9fcb3c79d66f256a696c51734ae05ffd06da1937d1b380aaafb5fa5b]
```

**Comment by ndegory** [comment]
the -f option will not allow you to create a cluster if the infrakit container is already created. It will only allow you to discard the infrakit configuration volume if it was not properly removed.

**Review by neha-viswanathan — APPROVED** [review]
Tested the verification steps. Works well. But was unable to test the `-f` option.

**Comment by subfuzion** [comment]
Closing and reopening to trigger a CI build.

**Comment by subfuzion** [comment]
@ndegory Looks like the build is failing because you have a dependency on the cli update pending in #862. I'll go ahead and fix it for you.

**Review by subfuzion — APPROVED** [review]
CI build passes now with the update to the ci config. The rest LGTM.

**Pull request merged**
