### PR TITLE
Agent default command

### PR DESCRIPTION
**Pull request by ndegory**
- default behavior of ampagent image is to check and install
- cloudformation template runs the ampagent at the end of the install

### CODE REVIEW

**Comment by nikolai-derzhak-distillery** [comment]
It about midnight in your timezone. Please calm down :)

**Comment by ndegory** [comment]
@nderzhak, in my original timezone it's time to go to the office ;)

**Comment by nikolai-derzhak-distillery** [comment]
I see. That is why :) You have really long lasting jet lag then.

**Comment by subfuzion** [comment]
https://www.brainyquote.com/quotes/authors/r/robert_frost.html

**Pull request merged**
