### PR TITLE
Better regular expressions for CLI tests

### PR DESCRIPTION
**Pull request by ndegory**
Refs #370 

Rewrite of regexp to be more accurate

How to check:

```
swarm start
go test ./cmd/amp/cli
```

has to be rebased after #386 has been merged.

### CODE REVIEW

**Review by subfuzion — APPROVED** [review]
I think overall these look like good improvements. However, I'm not sure that changing the code to use posix character classes -- requiring an extra pair of enclosing brackets -- is worth the effort just for space, and without consensus and guidance, it's an arbitrary change on your part. I'm not opposed, although to me `\s` is just as readable and a lot less verbose than `[[:space:]]`, and the nuances between perl and posix and non-ASCII support don't really matter here. Of course, once you move beyond `\s`, '`\d`, `\w` classes, `[[:alnum:]]`, `[[:alpha:]]`, `[[:blank:]]`, `[[:lower:]]`, `[[:punct:]]`, `[[:upper:]]`, and `[[:xdigit:]]` become more readable. On that note, I wonder if we're accepting `[[:space:]]` in cases where `[[:blank:]]` is more appropriate? Anyway, we'll move all these into a standard regex dictionary and we can fine tune as needed. Thanks.

**Comment by subfuzion** [comment]
@ndegory Please resolve conflicts so this can be merged. @bquenin's PR renamed the associated files.

**Comment by ndegory** [comment]
@subfuzion I'll revert the [[:space:]] to \s if you prefer, anyway it's anecdotal, the main change is that the regexp now are matching different outputs.

**Comment by subfuzion** [comment]
👍

**Pull request merged**
