### PR TITLE
fix the port mappings for amplifier on the Swarm cluster

### PR DESCRIPTION
**Pull request by ndegory**
The connection from the containerized AMP CLI to Amplifier in the bootstrapped Swarm cluster is failing due to a wrong port mapping in the default configuration.

- fix the port mapping for Amplifier

### CODE REVIEW

**Review by bquenin — APPROVED** [review]
LGTM

**Comment by subfuzion** [comment]
@ndegory Please make sure your PR works when submitting! I pushed additional fixes to resolve the issue for the time being. Inside of `hostnet` amp needs to connect to `m1` (or any swarm node) that has published `50101`. I updated the makefile to ensure client updates get built.

Please verify on your end:

    $ amp build-cli
    $ amp version

**Comment by ndegory** [comment]
```
$ ampmake build-cli
$ amp version
MP:
 Version:       v0.6.0-dev
 Build:         3ba0ae1b
 ConfigAddr:    m1:50101
 Go version:    go1.7.4
 OS/Arch:       linux/amd64
Error connecting to amplifier @ m1:50101: grpc: timed out when dialing
$ amp start
$ docker run -it --rm --network=hostnet -v $PWD/stacks:/stacks docker --host=m1 stack deploy -c /stacks/amplifier.stack.yml amplifier
$ amp version
AMP:
 Version:       v0.6.0-dev
 Build:         3ba0ae1b
 ConfigAddr:    m1:50101
 Go version:    go1.7.4
 OS/Arch:       linux/amd64

Amplifier:
 Version:       v0.6.0-dev
 Port:          :50101
 Go version:    go1.7.4
 OS/Arch:       linux/amd64
```

**Comment by subfuzion** [comment]
👍

**Pull request merged**
