### PR TITLE
Consolidated repository with all Docker images

### LINKED ISSUE #711: Merge AMP images code in AMP repo
AMP repo should include all the images we build specifically for AMP.

To be moved to images folder:
- [x] appcelerator/docker-influxdb-amp
- [x] appcelerator/docker-telegraf
- [x] appcelerator/docker-kapacitor-amp
- [x] appcelerator/docker-grafana-amp
- [ ] appcelerator/docker-haproxy
- [x] appcelerator/docker-elasticsearch-amp
- [x] appcelerator/docker-etcd
- [x] appcelerator/docker-amp-nats-streaming
- [x] appcelerator/docker-pinger

And new rules should be added to the Makefile to build these images and push them on Docker hub.

- [ ] Once moved, the original repos should have a warning in the readme pointing to the amp repo.

### PR DESCRIPTION
**Pull request by ndegory**
Fix #711 

- images are moved in the AMP repo (all but haproxy, it includes vendoring and will have to be managed differently)

how to test:
- images/build-images.sh # should build all images with tag ```latest```

### CODE REVIEW

**Review by JosephGJ — APPROVED** [review]
Tested. LGTM

**Comment by ndegory** [comment]
rebased on mater

**Review by subfuzion — APPROVED** [review]
Thanks @ndegory 👍

**Comment by jhaynie** [comment]
finally a mono repo. 👍

**Pull request merged**
