### PR TITLE
amp cluster create - support local plugin

### PR DESCRIPTION
**Pull request by bquenin**
Relates to #1591 
Depends on `amp-local` image for build to succeed before merging.

Refactored `amp cluster` commands to prepare for local plugin.

### CODE REVIEW

**Comment by subfuzion** [comment]
I guess we're waiting on `amp-local` for the build to succeed.

**Comment by ndegory** [comment]
yes, I should be able to push amp-local today.

**Comment by subfuzion** [comment]
OK, I updated the description to reflect dependency.

**Comment by subfuzion** [comment]
Close/reopen to trigger CI build

**Pull request merged**
