### PR TITLE
Volume mounts for registry and etcd (#278)

### LINKED ISSUE #278: Add Persistence to etcd container
# Background

When the swarm restarts, stacks and services that have been previously created are left in an orphaned state, rendering amp cli unable to stop and remove.
# Solution

Add a mount to the etcd swarm command that will cause the etcd `<k,v>` to persist between restarts. 

For example,

```
 --mount type=bind,source=/etcd/data,target=/etcd-data \
    -e ETCD_DATA_DIR=/etcd-data \
```

Thoughts?

### PR DESCRIPTION
**Pull request by ndegory**
resolves #278
- replace bind mount of registry service by a volume mount
- add a volume mount on etcd service

### CODE REVIEW

**Review by chrisccoy — APPROVED** [review]
- Started the Swarm
- Created a Stack
- Restarted the Swarm
  
  Stack was still visible in  etcd
- Stopped Stack
- Removed Stack
  
  Previously, this was not possible. 

As long as everyone is on board with using the volume approach, LGTM.

**Comment by ndegory** [comment]
I also checked with the registry service:
- swarm start --min
- docker push localhost:5000/whatever-image
- docker ps | grep registry
- docker kill _registry-container-id_
- wait for the service to bring back a new container
- check that the image is still in the registry: curl localhost:5000/v2/_catalog

**Comment by chrisccoy** [comment]
:+1:

**Comment by subfuzion** [comment]
LGTM 👍

**Pull request merged**
