### PR TITLE
Haproxy reverse proxy amplifier service

### PR DESCRIPTION
**Pull request by freignat91**
#112
- add option --service for amplifier, if exist it uses swarm addresses, if not it uses localhost addresses
- add option --server for amp, if exist it uses the value to found amplifier server, if not it use localhost:50101
- add build-server-image entry in Makefile to build the appcelerator/amplifier:lastest image
- update swarm file to create network amp-public and add amplifier service on networtk amp-public
- update HAProxy to reserse proxy GRPC connection from 8080 to amplifier

test on the 'haproxy' branch
- rm -rf vendor
- glide install
- make
- ./swarm pull
- ./swarm start

the image appcelerator/amplifier:latest is used for the service amplifier.
It's possible to rebuild it using the command:
make build-server-image

when all services are started:
- ./amp logs  --server localhost:8080 ->  call the service amplifier through HAProxy and run the command logs
- ./amp logs -> try to reach local amplifier server and generate error
- ./amplifier --clientid [your id] -- clientsecret [your secret]  -> launch local amplifier server
- ./amp logs -> call the local amplifier server and execute the command logs
- ./amp logs  --server localhost:8080 -> verify that the command on the amplifier service still works

To test on Amazon try (only if your firewall policy let port 8080 open for AWS IP, if not needs IT Request)
- ./amp stats --server 52.210.103.91:8080 --service

you should get the AWS amp test environment services stats

AWS amp test UI is available here: http://52.210.103.91/ui/
(need firewall port 80 open for aws machines)

### CODE REVIEW

**Comment by generalhenry** [comment]
:+1:

**Comment by generalhenry** [comment]
Tested locally.

**Comment by subfuzion** [comment]
A few things to note: the description doesn't mention that the `appcelerator/amplifier` image needs to be built. It can be deduced from inspecting the changes, but the description should make clear. The makefile should have a rule for building it so that it's standardized for everyone (there is currently a `build-image` rule, but that's for `amp`; we should probably have a `build-amplifier-image` rule). Finally, this does force on our workflow the necessity to build the image and stop and start the amplifier service in the amp swarm each time we update it. This will get tedious. We definitely should have make rules or a shell script to ease this, and we should really consider making it possible to continue localhost development an alternative option...  But other that this feedback, the PR itself looks great. 👍

**Comment by freignat91** [comment]
Please don't merge this PR, preparing update for amplifier local usage

**Comment by subfuzion** [comment]
Successfully tested localhost and amazon. I have an issue testing amplifier in the swarm, but it seems to be isolated to Docker for Mac at the moment since it's passing for everyone else running on Linux. Good work! 👍

**Pull request merged**
