### PR TITLE
Add etcd to swarm

### PR DESCRIPTION
**Pull request by subfuzion**
Closes https://github.com/appcelerator/amp-project/issues/330

This PR adds `etcd` to the `swarm` script.

Verification:

```
$ docker run --rm --net=host -e ETCDCTL_API=3 quay.io/coreos/etcd:v3.0.4 etcdctl put foo bar
OK
$ docker run --rm --net=host -e ETCDCTL_API=3 quay.io/coreos/etcd:v3.0.4 etcdctl get foo
bar
```

### CODE REVIEW

**Comment by freignat91** [comment]
it's ok, but it misses 
--label amp.swarm="infrastructure" \
for etct, otherwise the remove function won't remove it

**Comment by subfuzion** [comment]
Thanks, good catch!

**Comment by subfuzion** [comment]
How ironic for me to forget that. Ok, label is added.

**Comment by freignat91** [comment]
tests ok

**Pull request merged**
