### PR TITLE
add registry to amp with HAProxy reverse proxy

### PR DESCRIPTION
**Pull request by freignat91**
Add registry as a service

Test:
- pull swarm all images (should have registry:2 in the list): `./swarm pull`
- start amp swarm: `sudo ./swarm start`
- create or pull an image for instance: `docker pull alpine`
- tag it:  `docker tag alpine localhost:5000/alpine`
- push it: `docker push localhost:5000/alpine`
  image is pushed in the amp registry going through HAProxy
- verify you can pull it: `docker pull localhost:5000/alpine` ,having this console message: Image is up to date for localhost:5000/alpline:latest
- `make install` (rm -rf vendor and glide install, if needed)
- `amp push localhost:5000/alpine` -> push the image using amp command

### CODE REVIEW

**Comment by bquenin** [comment]
Tested and working

**Comment by generalhenry** [comment]
Failing on docker for mac in service mode, working in run mode.

**Comment by generalhenry** [comment]
Failing on docker for mac in service mode, using localhost:500/imagename, working on 127.0.0.1:5000/imagename

**Comment by subfuzion** [comment]
As noted, issues with OS X require using `127.0.0.1` instead of `localhost` for this to work. Also seeing errors that appear to be related to build service (will discuss with @generalhenry). But otherwise is working, looks good.

**Pull request merged**
