### PR TITLE
disable the net input for the telegraf telemetry worker (kafka consumer)

### PR DESCRIPTION
**Pull request by ndegory**
#83
- the appcelerator/telegraf image now has a new env variable to enable/disable the net plugin, disables the net plugin of telegraf for the kafka consumer in swarm

### CODE REVIEW

**Comment by subfuzion** [comment]
@ndegory Have you verified?

**Comment by subfuzion** [comment]
Sorry, I meant to ask @chrisccoy if he has verified this.

**Comment by chrisccoy** [comment]
:+1: 

As verification, The net measurement previously was showing entries for the telegaf-agent, but these have been silenced.

**Comment by subfuzion** [comment]
Sounds good. Thanks @ndegory and @chrisccoy 👍

**Pull request merged**
