### PR TITLE
Add grpc-gw usage example

### PR DESCRIPTION
**Pull request by generalhenry**
ref: https://github.com/appcelerator/amp/issues/425

Add a example of using the amplifier-gateway api to build a ui

To test:
`./shrink.sh local`
`amp pf start --local`
`cd examples/ui`
`./deploy.sh`
open http://www.gw-ui.local.atomiq.io/stacks/

### CODE REVIEW

**Review by chrisccoy — APPROVED** [review]
:+1: works like a charm.

**Comment by chrisccoy** [comment]
FYI- You may get  a protobuf error:
```
Error during: amp up, reason: rpc error: code = 2 desc = proto: can't skip unknown wire type 7 for stack.Stack
```
 if you do not perform a `make install` prior to the deploy step

**Review by JosephGJ — APPROVED** [review]
LGTM. Had to open link in a chrome window rather than safari.

**Comment by generalhenry** [comment]
re: safari
I built it using new browser features, and safari is missing one of them (fetch) it's easy to polyfill but for now the browser support matrix is [chrome 55+] though it should also be working in firefox, opera and edge.  (safari is sadly the new IE)

**Review by bquenin — APPROVED** [review]
LGTM, tested on linux with Chrome 55

**Pull request merged**
