### PR TITLE
Full test suite for amp logs

### PR DESCRIPTION
**Pull request by bquenin**
#11

In order to test this PR:

```
docker-compose -f docker-compose.test.yml build sut
docker-compose -f docker-compose.test.yml up
```

OR, you can start the swarm:

```
./swarm start --min
make test-logs
```

### CODE REVIEW

**Comment by subfuzion** [comment]
@bertrand-quenin You are missing a dependency.

```
$ make test-logs
# github.com/appcelerator/amp/api/rpc/logs
package github.com/appcelerator/amp/api/rpc/logs_test
        imports github.com/stretchr/testify/assert
        imports github.com/pmezard/go-difflib/difflib: cannot find package "github.com/pmezard/go-difflib/difflib" in any of:
        /Users/tony/projects/go/src/github.com/appcelerator/amp/vendor/github.com/pmezard/go-difflib/difflib (vendor tree)
        /usr/local/go/src/github.com/pmezard/go-difflib/difflib (from $GOROOT)
        /Users/tony/projects/go/src/github.com/pmezard/go-difflib/difflib (from $GOPATH)
FAIL    github.com/appcelerator/amp/api/rpc/logs [setup failed]
make: *** [test-logs] Error 1
```

**Comment by subfuzion** [comment]
@bertrand-quenin You're instructions are wrong for the second part. If you start `amplifier` first, then the tests fail:

```
$ make test-logs
2016/08/27 12:29:06 connecting to etcd at http://localhost:2379
2016/08/27 12:29:06 connected to etcd at http://localhost:2379
2016/08/27 12:29:06 connecting to elasticsearch at http://localhost:9200
2016/08/27 12:29:06 connected to elasticsearch at http://localhost:9200
2016/08/27 12:29:06 connecting to kafka at localhost:9092
=== RUN   TestShouldGetAHundredLogEntriesByDefault
2016/08/27 12:29:06 connected to kafka at localhost:9092
2016/08/27 12:29:06 connecting to InfluxDB at http://localhost:8086
2016/08/27 12:29:06 connected to influxDB at http://localhost:8086
2016/08/27 12:29:06 amplifer is unable to listen on: 50101
listen tcp :50101: bind: address already in use
exit status 1
FAIL    github.com/appcelerator/amp/api/rpc/logs        0.038s
```

**Comment by subfuzion** [comment]
@ndegory Test failures (I believe `TestShouldGetAHundredLogEntriesByDefault` failure is due to https://github.com/appcelerator/amp/issues/70)
@bertrand-quenin `TestShouldFilterByContainerId` should assert the range and fail, not panic. 

```
$ make test-logs
2016/08/27 12:29:46 connecting to etcd at http://localhost:2379
2016/08/27 12:29:46 connected to etcd at http://localhost:2379
2016/08/27 12:29:46 connecting to elasticsearch at http://localhost:9200
2016/08/27 12:29:46 connected to elasticsearch at http://localhost:9200
2016/08/27 12:29:46 connecting to kafka at localhost:9092
=== RUN   TestShouldGetAHundredLogEntriesByDefault
2016/08/27 12:29:46 connected to kafka at localhost:9092
2016/08/27 12:29:46 connecting to InfluxDB at http://localhost:8086
2016/08/27 12:29:46 connected to influxDB at http://localhost:8086
2016/08/27 12:29:46 amplifier is listening on port 50101
--- FAIL: TestShouldGetAHundredLogEntriesByDefault (60.39s)
        Error Trace:    logs_test.go:119
        Error:          Not equal: 100 (expected)
                                != 0 (actual)

=== RUN   TestShouldFilterByContainerId
--- FAIL: TestShouldFilterByContainerId (0.01s)
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range
```

**Comment by subfuzion** [comment]
@bertrand-quenin  I rebased your PR with `master` and I added the missing dependencies. Since I rebased, you will need to reset your branch:

```
$ git fetch origin 11-tests
$ git reset --hard origin/tests
```

**Comment by subfuzion** [comment]
@bertrand-quenin @chrisccoy Can't merge the PR in the current state (commit history doesn't right to me). I'll take another look after #93 is merged and this PR is rebased on it.

**Comment by bquenin** [comment]
@subfuzion The history is fine, I just rebased the branch on master. Already went through dozen of conflicts. Creating a separate branch for updating the dependencies is not going to help IMHO.

**Comment by subfuzion** [comment]
@bertrand-quenin I'll wait for https://github.com/appcelerator/amp/pull/93 to be merged and rebase from there and then look things over. There are other issues (for example 1872e22df79dd8fcf9713d2218a01f2c81d708a6 shouldn't be there). If you had rebased, then none of the changes that were already in master that have nothing to do with your PR (like all the stats additions and other refactoring) would be showing up on your commit history.

**Comment by subfuzion** [comment]
Closing this PR. It has been superseded by #93 and #95.

**Pull request closed without merging**
