### PR TITLE
Leverage Swarm events in pre deployment checks

### PR DESCRIPTION
**Pull request by ndegory**
Use the SwarmKit events to validate service task creation and task stability

## Verification
on a swarm manager node,
```
cd cluster/agent
make image
docker run --rm -v /var/run/docker:/var/run/docker:ro -v /var/run/docker.sock:/var/run/docker.sock:ro appcelerator/ampagent check -a
```
it should output something similar to:
```
2017/07/07 06:46:03 Docker engine version 17.06.0-ce
2017/07/07 06:46:03 passed - api version = 1.3

2017/07/07 06:46:03 creating network amptest
2017/07/07 06:46:03 creating service check-server
2017/07/07 06:46:04 expected event count reached
2017/07/07 06:46:04 Task creation events successfuly read
2017/07/07 06:46:04 creating service check-client
2017/07/07 06:46:06 expected event count reached
2017/07/07 06:46:06 Task creation events successfuly read
2017/07/07 06:46:12 timeout reached while waiting for events
2017/07/07 06:46:12 No dropped task
2017/07/07 06:46:17 Counting request success rate
2017/07/07 06:46:17 Removing service check-client (qwnxx1vou9kecndrjoto2gjos)
2017/07/07 06:46:19 Removing service check-server (y0f581wi1o3asknlu31xn05c0)
2017/07/07 06:46:21 removing network amptest (kdwaqni6btdr2sod0ucrlpbcx)
2017/07/07 06:46:21 passed - 1105 connections / 1105 success
```

### CODE REVIEW

**Review by subfuzion — CHANGES_REQUESTED** [review]
@ndegory looking good, but the process exits with 1. I added a Makefile rule (`run-checks`), so this causes `make` to fail.

**Comment by ndegory** [comment]
@subfuzion 
when I run `make run-checks` it returns 0. If you have a non zero return code that means the checks really failed. Since it tests the prerequisites, that means you may have something missing on your system, maybe the labels.

**Comment by subfuzion** [comment]
@ndegory Then the verification steps in the description are not complete and/or the checks don't respond with enough information for diagnosing failure. I'm not trying to troubleshoot/debug, just verify, so I guess from my perspective the checks need to provide more diagnostic output (after all, that's what the checks are for in the first place -- to help us pinpoint causes of failure during cluster checks before deploying amp services).

**Comment by ndegory** [comment]
sure, I'll add more diagnostic information.

**Comment by ndegory** [comment]
more checks have been added to the ampagent.

**Review by subfuzion — APPROVED** [review]
LGTM

**Pull request merged**
