### PR TITLE
Adds storage update support

### PR DESCRIPTION
**Pull request by subfuzion**
#10

Adds initial update support for the k/v store. This does not close the issue and does not yet implement guaranteed updates with a retry function for resolving conflicts. This is just meant to be a small PR to continue fleshing out more of the storage interfaces.
## Verification

```
$ ./swarm start etcd
$ make test-storage
```

### CODE REVIEW

**Comment by chrisccoy** [comment]
I am having an issue with the code:
```
# github.com/appcelerator/amp/data/storage/etcd
data/storage/etcd/store.go:39: cannot use etcd literal (type *etcd) as type storage.Interface in return argument:
        *etcd does not implement storage.Interface (wrong type for Create method)
                have Create("github.com/appcelerator/amp/vendor/golang.org/x/net/context".Context, string, "github.com/appcelerator/amp/vendor/github.com/golang/protobuf/proto".Message, "github.com/appcelerator/amp/vendor/github.com/golang/protobuf/proto".Message, int64) error
                want Create("github.com/appcelerator/amp/vendor/github.com/appcelerator/amp/vendor/golang.org/x/net/context".Context, string, "github.com/appcelerator/amp/vendor/github.com/appcelerator/amp/vendor/github.com/golang/protobuf/proto".Message, "github.com/appcelerator/amp/vendor/github.com/appcelerator/amp/vendor/github.com/golang/protobuf/proto".Message, int64) error
# github.com/appcelerator/amp/data/storage/etcd_test
data/storage/etcd/store_test.go:137: store.Update undefined (type storage.Interface has no field or method Update)
FAIL    github.com/appcelerator/amp/data/storage/etcd [build failed]
Makefile:95: recipe for target 'test-storage' failed
make: *** [test-storage] Error 2
```

**Comment by subfuzion** [comment]
The [interface](https://github.com/appcelerator/amp/pull/41/commits/045dafc0514603d81d98404948eeed55ede3bdaa#diff-6d36ff2f22be8fe2d4c83d7dc00dddacR40) and the etcd [implementation](https://github.com/appcelerator/amp/pull/41/commits/045dafc0514603d81d98404948eeed55ede3bdaa#diff-930f2481a441b2c43168d9129724fa67R123) are both part of the PR. Are you sure you're on the PR branch?

**Comment by generalhenry** [comment]
Passing for me locally

**Comment by generalhenry** [comment]
The CI is failing, but not on the new tests

**Comment by chrisccoy** [comment]
LGTM.

**Pull request merged**
