### PR TITLE
update doc with new amp commands

### PR DESCRIPTION
**Pull request by freignat91**
related to #470

Update documentation with new amp commands usages and options

### CODE REVIEW

**Comment by generalhenry** [comment]
There's also a reference in https://github.com/appcelerator/amp/tree/master/examples

**Comment by freignat91** [comment]
Example doc updated

**Review by bquenin — COMMENTED** [review]
We should probably also mention that the swarm needs to be created beforehand (with docker swarm init for instance, or `amp-swarm-deploy`)

**Review by bquenin — APPROVED** [review]
LGTM

**Pull request merged**
