### PR TITLE
[v0.6.x] Adding support for Team Storage

### PR DESCRIPTION
**Pull request by chrisccoy**
WIP: Added support for Team storage to etcd

### CODE REVIEW

**Comment by chrisccoy** [comment]
@generalhenry  Build seems to have intermittent issues? Should we clean dangling/stopped containers as a precursor?

**Comment by generalhenry** [comment]
@chrisccoy yeah open up an issue, we need clean CI

**Comment by chrisccoy** [comment]
Issue #720 created

**Comment by chrisccoy** [comment]
@generalhenry slow progress for me today, trying to absorb the master detail relationships, but I think I have it working. I think we should segregate the interface into data/business (eg, "Verify" is incongruent to data storage, but makes sense for business) I think we should focus on CRUD for the data layer and provide an additional layer for CLI to use (business for a lack of nomenclature). 

`biz->uses->datalayer->uses->storage`

I do not want to over engineer, but the data layer with etcd needs a pattern. Thoughts?

**Comment by chrisccoy** [comment]
I think it helps to visulaize, so here is how storage looks after tests, so far:
(you can also try [this](https://gist.github.com/chrisccoy/0cf5026173ebad017d51acdddaf623fd), but you must run the integration-test, first.)

```
amp-test/accounts/account/id/271aa763b7fd7c79c1c60a9a47b88817aeb0b9a9896f3c0936bdd2102af0d349

amp-test/accounts/account/id/58c25ad009a2072f32b86832f2b18457c27e0bf7e04175032fd939426e9a7677

amp-test/accounts/account/id/9ccd2d0685a85728b3da52c7592cf4691e3dbab8aed8f105f3e0c53a17e00860

amp-test/accounts/account/name/axway

amp-test/accounts/account/name/axway2

amp-test/accounts/account/name/theuser

amp-test/accounts/team/id/4b4c75cbc4bc042eed92597a3931187fc57f1e7d6c540819fafee1b70707b135

amp-test/accounts/team/member/4b4c75cbc4bc042eed92597a3931187fc57f1e7d6c540819fafee1b70707b135/04fee120e36e8c5e5548c7e83b14c552602636db38286013157ecc7b78dc3977

amp-test/accounts/team/name/Falcons
```
Lots of work to be done, but coming together.

**Comment by chrisccoy** [comment]
I am going to resubmit after #727 is merged

**Pull request closed without merging**
