### PR TITLE
Stack 1.13

### PR DESCRIPTION
**Pull request by freignat91**
Related to #733 

#738 should be merged first

refactor amp stack to use Docker 1.13 way of managing them.

to test:

- amp pf stop amp (stop amp old way)
- make install (clean before could be required)
- make TAG=local build-image
- amp pf start --local all

- - amp pf monitor (in the separated console)
- - amp pf start --local -> start only ampcore
- - amp logs -> error 
- - amp pf start amplog --local (wait for stack started)
- - amp logs --infra -> a lot of logs...
- - amp pf stop amplog
- - amp stats -> error
- - amp pf start ampmonitor --local (wait for stack started, and wait a while to have some data)
- - amp stats -> a lot of metrics
- - amp pf stop ampmonitor
- - amp pf start ampfunction --local
- - cd examples/functions/demo-function
- - make image
- - amp fn create test appcelerator/amp-demo-function
- - cat Makefile | curl fn.ampfunction.local.appcelerator.io/test --data-binary @-
- -> function executed
- - amp pf stop ampfunction
- - cd ../../.. (back to amp home)
- - amp pf start ampadmin --local (wait stack is started)
- - amp node ls -> see your host information
- - amp node count -> see your stopped container
- - amp node purge --container -> container deleted
- - amp node count -> see you don't have stopped container anymore
- - amp pf stop ampadmin
- - amp stack up test -c api/rpc/stack/test_samples/sample-03.yml (wait stack is started)
- - curl www.test.local.appcelerator.io/ping -> pong
- - amp stack ps test  -> list task
- - amp stack services test -> list services
- - amp stack rm test
- - amp stack ps ampcore -> see it's working also for infra stack
- - amp stack services ampcore -> same

autmated tests:
- amp pf stop (wait all is down)
- amp pf start all --local -v  (wait all is up)
- make test

-

### CODE REVIEW

**Comment by subfuzion** [comment]
@freignat91 I will start to review, but we have a convention for the team that we have discussed in the past. To make dealing with vendoring easier (as well as to make the GitHub review for your specific PR easier since vendor updates includes 1000's of files), we submit a separate PR for the proposed vendor updates, followed by the PR with the code updates. I'll be looking at some of the vendor update conflicts later today that I had noticed previously, so I might be able to submit the vendor PR for you. I'll let you know.

**Comment by freignat91** [comment]
ok, no problem

**Comment by subfuzion** [comment]
@freignat91 This is looking good. We still have a bunch of work to get this integrated with the new build system. I just a pushed a commit that merges this with the latest of all the vendor updates (from #738) and includes a number of other changes and fixes. Also, I took the liberty of renaming `amp.var` to `amp.manifest`, which is what I asked for.

You forgot that I wanted your PR to be submitted against stackv3, not master. It looks like someone deleted the branch, so I just recreated it again. Please update this PR to merge against `stackv3`. Thanks.

team-chat

**Review by subfuzion — CHANGES_REQUESTED** [review]
Please resubmit PR against stackv3 as requested. Thanks.

**Comment by freignat91** [comment]
ok, i close this one and open a new one

**Comment by subfuzion** [comment]
Will reopen the PR once it is [based against](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) the [`stackv3` branch](https://github.com/appcelerator/amp/tree/stackv3) as requested.

**Pull request closed without merging**
