### PR TITLE
Bootstrap network check

### PR DESCRIPTION
**Pull request by ndegory**
Improve robustness of bootstrap process.

- containers are auto removed when killed (better test experience)
- Docker Swarm DNS resolution check at end of init, container is killed if test fails
- update the etcd image (quits early in case of DNS issues)

how to test:
```
hack/deploy
```
the services should all stabilize.

PS: you can monitor the container initialization in the InfraKit logs:
```
docker logs -f instance-plugin-docker 2>&1 | grep exec
time="2017-04-05T17:43:41Z" level=debug msg="exec the init script"
time="2017-04-05T17:43:49Z" level=debug msg="Init script succesfully executed"
```
These two lines will appear for each successfully initialized node. Be aware that initialization failure can come from other things than DNS issues.

### CODE REVIEW

**Comment by bquenin** [comment]
It doesn't work on linux:

```
$ docker exec m1 nslookup m1
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	m1
Address: 172.19.0.5

$ docker exec m1 nslookup m2
Server:		127.0.0.11
Address:	127.0.0.11#53

** server can't find m2: NXDOMAIN

$ docker exec m1 nslookup m3
Server:		127.0.0.11
Address:	127.0.0.11#53

** server can't find m3: NXDOMAIN
```

After 2 or 3 minutes waiting, the resolution works:
```
$ docker exec m1 nslookup m1
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	m1
Address: 172.19.0.5

$ docker exec m1 nslookup m2
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	m2
Address: 172.19.0.9

$ docker exec m1 nslookup m3
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	m3
Address: 172.19.0.8

```

**Comment by bquenin** [comment]
With the latest changes, the swarm cluster never gets deployed on my machine. Nodes keep failing and restarting and eventually, the timeout is reached.

**Comment by freignat91** [comment]
On my mac, it works 3 times and failed the forth one, at the end, two nodes which has no swarm dns working have not been re-created and stay like that until the script timeout

**Review by subfuzion — APPROVED** [review]
We still haven't identified or resolved the underlying network issue, but merging this PR to move forward on the next iteration of enhancements and CI checks to get us where we want to be.

**Pull request merged**
