### PR TITLE
elasticsearch 5

### LINKED ISSUE #618: Upgrade to ElasticSearch 5
AMP should move to the latest version of ElasticSearch (5).
AMP is already using the client API of version 5, so there should not be any issue in the update.

### PR DESCRIPTION
**Pull request by ndegory**
closes #618 

- elasticsearch 5

test with:
- make clean install
- make TAG=local build-image
- amp pf stop ; amp pf pull && amp pf start --local && make test

### CODE REVIEW

**Comment by ndegory** [comment]
tested on Docker for Mac (1.12.5) ✅

**Comment by ndegory** [comment]
failing on Linux (Docker 1.12.5): elasticsearch fails to start

**Comment by ndegory** [comment]
passing on Linux Docker 1.12.5 now.

**Review by bquenin — APPROVED** [review]

**Review by bquenin — APPROVED** [review]
LGTM (tested on linux, docker 1.12.5)

**Review by freignat91 — APPROVED** [review]
Refactor to let infrastructure.go file as a config file only
Add the same prerequisite to ampadm

**Comment by ndegory** [comment]
thanks @freignat91 , LGTM

**Pull request merged**
