### PR TITLE
Revendoring (#500, part 1)

### LINKED ISSUE #500: Unstable vendor dependencies
Some of the dependencies listed in the glide lock file are not based on tags or branches. Regenerating the glide.lock breaks some features.

- docker/docker is from an old commit on the master branch (before the 1.13.0* tags were set)
- grpc has no version property

### PR DESCRIPTION
**Pull request by ndegory**
Fixes #500 

Still in progress: wait for Docker 1.13.0 rc3 for a fix on the API.

- update the glide.yaml for better management of vendors (depending on a master branch is not stable)
- update AMP code to adjust to the changes
- update the glide.lock and the vendor (beware, big diff)

How to test:
- make install
- amp pf pull --local
- amp pf start --local
- make test
- cli test

### CODE REVIEW

**Comment by ndegory** [comment]
the change on platform_manager.go is not working, amp pf start can't find the images.

**Comment by bquenin** [comment]
Yeah I had the same issue while testing

**Comment by ndegory** [comment]
I've included a workaround on the amp pf start issue (a new reference filter in the ImageList API not accepted by Docker 1.12). The tests are now passing.
I leave to the reviewers the decision to include or not the Docker vendoring commit.

**Comment by bquenin** [comment]
My preference would be to wait for docker 1.13 to be released and then update our vendors.

**Comment by ndegory** [comment]
Checking with the Docker people if it's a normal behavior of the library...

**Comment by ndegory** [comment]
we should wait for Docker 1.13 RC3: https://github.com/docker/docker/issues/28895

**Comment by ndegory** [comment]
The issue is fixed in Docker repo branch 1.13.x, I used it for the vendors, it works great now!

**Review by freignat91 — APPROVED** [review]
LGTM

**Pull request merged**
