### PR TITLE
Add grpc gateway runtime, adjust docker api usage

### PR DESCRIPTION
**Pull request by generalhenry**
Sets stage for https://github.com/appcelerator/amp/issues/425

### CODE REVIEW

**Comment by chrisccoy** [comment]
@generalhenry I assume the large number of vendor changes are anticipated?

**Comment by generalhenry** [comment]
@chrisccoy yes, that's why this is isolated into it's own commit (so the real code changes don't have this kind of noise)

**Review by chrisccoy — COMMENTED** [review]
LGTM. 
I noticed the subpackage for glide only includes `runtime` - does this replace the prior reference to the `protoc-gen-` subpackages or are they just not needed?

**Comment by generalhenry** [comment]
The protoc-gen- packages aren't needed in this repo, they're used to build, not to run.

I added them here: https://github.com/appcelerator/docker-protoc/pull/2

**Review by chrisccoy — APPROVED** [review]
+1

**Pull request merged**
