### PR TITLE
Updating vendor to use kafka admin client

### PR DESCRIPTION
**Pull request by bquenin**
Updating vendor to be able to use kafka admin API
## Verification

```
$ rm -rf ~/.glide glide.lock vendor
$ make
```

### CODE REVIEW

**Comment by subfuzion** [comment]
Verification:

```
$ glide cc # also gets ride of ~/.glide cache
$ glide install
$ make test
$ make
```

**Comment by subfuzion** [comment]
@bertrand-quenin Getting errors related to version dependency conflicts and so made an attempt to resolve, but so far no luck (make sure you delete the glide cache in your home directory also: `glide cc` or `rm -rf ~.glide`). I think I might prefer to bring the `amp-docker-kafka` package into this project but I'm also considering other strategies at the moment. Will circle back with you and in the meantime, you can take as stab at resolving the dependency issues.

**Comment by bquenin** [comment]
@tony Can you please copy/paste your output ?
Here is mine:

```
bq@home  ~/go/src/github.com/appcelerator/amp   kafka-admin-vendor ± glide cc && rm -rf vendor ~/.glide glide.lock
[INFO]  Glide cache has been cleared.
 bq@home  ~/go/src/github.com/appcelerator/amp   kafka-admin-vendor ± glide install
[INFO]  Lock file (glide.lock) does not exist. Performing update.
[INFO]  Downloading dependencies. Please wait...
[INFO]  --> Fetching gopkg.in/yaml.v2.
[INFO]  --> Fetching golang.org/x/net.
[INFO]  --> Fetching github.com/docker/go-connections.
[INFO]  --> Fetching github.com/golang/protobuf.
[INFO]  --> Fetching github.com/docker/docker.
[INFO]  --> Fetching github.com/docker/distribution.
[INFO]  --> Fetching github.com/mitchellh/go-homedir.
[INFO]  --> Fetching github.com/Shopify/sarama.
[INFO]  --> Fetching github.com/appcelerator/amp-docker-kafka.
[INFO]  --> Fetching gopkg.in/olivere/elastic.v3.
[INFO]  --> Fetching github.com/google/go-github.
[INFO]  --> Fetching github.com/spf13/cobra.
[INFO]  --> Fetching github.com/fatih/color.
[INFO]  --> Fetching github.com/howeyc/gopass.
[INFO]  --> Fetching github.com/coreos/etcd.
[INFO]  --> Fetching github.com/influxdata/influxdb.
[INFO]  --> Fetching github.com/spf13/viper.
[INFO]  --> Fetching google.golang.org/grpc.
[INFO]  --> Fetching golang.org/x/oauth2.
[INFO]  --> Fetching github.com/spf13/pflag.
[INFO]  --> Fetching github.com/stretchr/testify.
[INFO]  --> Setting version for github.com/golang/protobuf to 1f49d83d9aa00e6ce4fc8258c71cc7786aec968a.
[INFO]  --> Detected semantic version. Setting version for github.com/docker/go-connections to v0.2.1.
[INFO]  --> Detected semantic version. Setting version for github.com/coreos/etcd to v3.1.0-alpha.1.
[INFO]  --> Detected semantic version. Setting version for github.com/docker/distribution to v2.5.1.
[INFO]  --> Detected semantic version. Setting version for github.com/stretchr/testify to v1.1.4.
[INFO]  --> Detected semantic version. Setting version for github.com/fatih/color to v1.0.0.
[INFO]  --> Detected semantic version. Setting version for github.com/influxdata/influxdb to v1.0.1.
[INFO]  --> Detected semantic version. Setting version for github.com/Shopify/sarama to v1.10.1.
[INFO]  --> Detected semantic version. Setting version for google.golang.org/grpc to v1.0.1-GA.
[INFO]  --> Detected semantic version. Setting version for gopkg.in/olivere/elastic.v3 to v3.0.54.
[INFO]  Resolving imports
[INFO]  --> Fetching github.com/davecgh/go-spew.
[INFO]  --> Fetching github.com/eapache/go-resiliency.
[INFO]  --> Fetching github.com/eapache/go-xerial-snappy.
[INFO]  --> Fetching github.com/eapache/queue.
[INFO]  --> Fetching github.com/klauspost/crc32.
[INFO]  --> Fetching github.com/google/go-querystring.
[INFO]  --> Fetching google.golang.org/appengine.
[INFO]  --> Fetching github.com/docker/go-units.
[INFO]  --> Fetching github.com/pkg/errors.
[INFO]  --> Fetching github.com/mattn/go-colorable.
[INFO]  --> Fetching github.com/mattn/go-isatty.
[INFO]  --> Fetching golang.org/x/crypto.
[INFO]  --> Fetching golang.org/x/sys.
[INFO]  --> Fetching github.com/inconshreveable/mousetrap.
[INFO]  --> Fetching github.com/fsnotify/fsnotify.
[INFO]  --> Fetching github.com/hashicorp/hcl.
[INFO]  --> Fetching github.com/magiconair/properties.
[INFO]  --> Fetching github.com/mitchellh/mapstructure.
[INFO]  --> Fetching github.com/pelletier/go-toml.
[INFO]  --> Fetching github.com/spf13/afero.
[INFO]  --> Fetching github.com/spf13/cast.
[INFO]  --> Fetching github.com/spf13/jwalterweatherman.
[INFO]  Found Godeps file in /home/bq/.glide/cache/src/https-github.com-influxdata-influxdb
[INFO]  --> Parsing GPM metadata...
[INFO]  --> Fetching github.com/ghodss/yaml.
[INFO]  --> Setting version for github.com/ghodss/yaml to 73d445a93680fa1a78ae23a5839bad48f32ba1ee.
[INFO]  --> Setting version for golang.org/x/net to 6acef71eb69611914f7a30939ea9f6e194c78172.
[WARN]  Conflict: google.golang.org/grpc version is ^1.0.1-GA, but also asked for 231b4cfea0e79843053a33f5fe90bd4d84b23cd3
[INFO]  google.golang.org/grpc reference 231b4cfea0e79843053a33f5fe90bd4d84b23cd3:
[INFO] - author: Qi Zhao <toqizhao@gmail.com>
[INFO] - commit date: Thu, 18 Aug 2016 17:22:36 -0700
[INFO] - subject (first line): Merge pull request #842 from menghanl/non_failfast_after_cc_close
[INFO]  Keeping google.golang.org/grpc ^1.0.1-GA
[WARN]  Conflict: github.com/golang/protobuf rev is currently 1f49d83d9aa00e6ce4fc8258c71cc7786aec968a, but github.com/coreos/etcd wants 8616e8ee5e20a1704615e6c8d7afcdac06087a67
[INFO]  github.com/golang/protobuf reference 1f49d83d9aa00e6ce4fc8258c71cc7786aec968a:
[INFO] - author: light <light@google.com>
[INFO] - commit date: Wed, 24 Aug 2016 20:12:15 +0000
[INFO] - subject (first line): Allow t/f and True/False while parsing text protos
[INFO]  github.com/golang/protobuf reference 8616e8ee5e20a1704615e6c8d7afcdac06087a67:
[INFO] - author: Ross Light <light@google.com>
[INFO] - commit date: Wed, 08 Jun 2016 14:55:45 -0700
[INFO] - subject (first line): ptypes: regen and remove transforms from regen.sh
[INFO]  Keeping github.com/golang/protobuf 1f49d83d9aa00e6ce4fc8258c71cc7786aec968a
[INFO]  --> Fetching github.com/golang/snappy.
[INFO]  --> Setting version for github.com/golang/snappy to d9eb7a3d35ec988b8585d4a0068e462c27d28380.
[INFO]  Found Godeps.json file in /home/bq/.glide/cache/src/https-github.com-docker-distribution
[INFO]  --> Parsing Godeps metadata...
[INFO]  --> Fetching github.com/Sirupsen/logrus.
[INFO]  --> Setting version for github.com/Sirupsen/logrus to 55eb11d21d2a31a3cc93838241d04800f52e823d.
[INFO]  --> Fetching github.com/Microsoft/go-winio.
[INFO]  --> Fetching github.com/opencontainers/runc.
[INFO]  --> Setting version for golang.org/x/sys to 9c60d1c508f5134d1ca726b4641db998f2523357.
[INFO]  --> Fetching github.com/pelletier/go-buffruneio.
[INFO]  --> Fetching github.com/pkg/sftp.
[INFO]  --> Fetching golang.org/x/text.
[INFO]  --> Fetching github.com/grpc-ecosystem/grpc-gateway.
[INFO]  --> Setting version for github.com/grpc-ecosystem/grpc-gateway to f52d055dc48aec25854ed7d31862f78913cf17d1.
[INFO]  --> Setting version for gopkg.in/yaml.v2 to 53feefa2559fb8dfa8d81baad31be332c97d6c77.
[INFO]  --> Setting version for google.golang.org/appengine to 12d5545dc1cfa6047a286d5e853841b6471f4c19.
[INFO]  Found Godeps.json file in /home/bq/.glide/cache/src/https-github.com-opencontainers-runc
[INFO]  --> Parsing Godeps metadata...
[INFO]  --> Fetching github.com/kr/fs.
[INFO]  --> Setting version for golang.org/x/crypto to c197bcf24cde29d3f73c7b4ac6fd41f4384e8af6.
[INFO]  Found Godeps.json file in /home/bq/.glide/cache/src/https-github.com-stretchr-testify
[INFO]  --> Parsing Godeps metadata...
[INFO]  --> Setting version for github.com/davecgh/go-spew to 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d.
[INFO]  --> Fetching github.com/pmezard/go-difflib.
[INFO]  --> Setting version for github.com/pmezard/go-difflib to d8ed2627bdf02c080bf22230dbb337003b7aba2d.
[INFO]  Downloading dependencies. Please wait...
[INFO]  Setting references for remaining imports
[INFO]  Exporting resolved dependencies...
[INFO]  --> Exporting github.com/spf13/cobra
[INFO]  --> Exporting github.com/golang/protobuf
[INFO]  --> Exporting github.com/docker/docker
[INFO]  --> Exporting github.com/howeyc/gopass
[INFO]  --> Exporting github.com/mitchellh/go-homedir
[INFO]  --> Exporting github.com/spf13/viper
[INFO]  --> Exporting github.com/google/go-github
[INFO]  --> Exporting github.com/Shopify/sarama
[INFO]  --> Exporting github.com/spf13/pflag
[INFO]  --> Exporting github.com/fatih/color
[INFO]  --> Exporting github.com/coreos/etcd
[INFO]  --> Exporting github.com/davecgh/go-spew
[INFO]  --> Exporting github.com/docker/distribution
[INFO]  --> Exporting github.com/influxdata/influxdb
[INFO]  --> Exporting github.com/appcelerator/amp-docker-kafka
[INFO]  --> Exporting github.com/docker/go-connections
[INFO]  --> Exporting github.com/docker/go-units
[INFO]  --> Exporting github.com/google/go-querystring
[INFO]  --> Exporting github.com/pkg/errors
[INFO]  --> Exporting github.com/eapache/queue
[INFO]  --> Exporting github.com/eapache/go-xerial-snappy
[INFO]  --> Exporting github.com/klauspost/crc32
[INFO]  --> Exporting github.com/mattn/go-colorable
[INFO]  --> Exporting github.com/inconshreveable/mousetrap
[INFO]  --> Exporting github.com/fsnotify/fsnotify
[INFO]  --> Exporting github.com/eapache/go-resiliency
[INFO]  --> Exporting github.com/mattn/go-isatty
[INFO]  --> Exporting github.com/mitchellh/mapstructure
[INFO]  --> Exporting github.com/magiconair/properties
[INFO]  --> Exporting github.com/hashicorp/hcl
[INFO]  --> Exporting github.com/spf13/cast
[INFO]  --> Exporting github.com/spf13/jwalterweatherman
[INFO]  --> Exporting github.com/golang/snappy
[INFO]  --> Exporting github.com/opencontainers/runc
[INFO]  --> Exporting github.com/spf13/afero
[INFO]  --> Exporting github.com/pelletier/go-toml
[INFO]  --> Exporting github.com/pelletier/go-buffruneio
[INFO]  --> Exporting github.com/Sirupsen/logrus
[INFO]  --> Exporting github.com/Microsoft/go-winio
[INFO]  --> Exporting github.com/ghodss/yaml
[INFO]  --> Exporting github.com/pkg/sftp
[INFO]  --> Exporting github.com/grpc-ecosystem/grpc-gateway
[INFO]  --> Exporting github.com/kr/fs
[INFO]  --> Exporting github.com/pmezard/go-difflib
[INFO]  --> Exporting github.com/stretchr/testify
[INFO]  --> Exporting golang.org/x/net
[INFO]  --> Exporting golang.org/x/oauth2
[INFO]  --> Exporting google.golang.org/grpc
[INFO]  --> Exporting golang.org/x/crypto
[INFO]  --> Exporting google.golang.org/appengine
[INFO]  --> Exporting golang.org/x/sys
[INFO]  --> Exporting golang.org/x/text
[INFO]  --> Exporting gopkg.in/olivere/elastic.v3
[INFO]  --> Exporting gopkg.in/yaml.v2
[INFO]  Replacing existing vendor dependencies
[INFO]  Project relies on 52 dependencies.
 bq@home  ~/go/src/github.com/appcelerator/amp   kafka-admin-vendor ± 
```

**Comment by bquenin** [comment]
After testing locally, I'm unable to use the imported code as it is part of a binary distribution with vendor.
I'm currently working on a library (https://github.com/appcelerator/amp-kafka-pilot) in order to reuse code in both projetcs (amp & and-docker-kafka).

**Pull request closed without merging**
