### PR TITLE
Add switch, whoami, logout commands to CLI

### PR DESCRIPTION
**Pull request by neha-viswanathan**
To test -

```
$ ampmake build
$ hack/dev
$ amp user signup 
$ amp login
$ amp whoami (currently logged in as user)
$ amp org create
$ amp switch (switch to newly created org)
$ amp whoami (currently logged in as org)
$ amp logout
```

### CODE REVIEW

**Review by subfuzion — COMMENTED** [review]
@neha-viswanathan LGTM, did you update the doc? Should make the update part of this PR...

**Review by bquenin — APPROVED** [review]
LGTM (tested on linux)

**Comment by neha-viswanathan** [comment]
Updated docs for the 3 commands. Docs for other commands will be a separate PR.

**Review by subfuzion — APPROVED** [review]
I'm going to merge this now, but would like to have this updated shortly to make it clearer that we are switching organizations with an `amp org switch` command (which implies that your own user id is an "org" you can switch back to).

**Pull request merged**
