### PR TITLE
Fixing environment variable in ampmake

### LINKED ISSUE #1706: Docker images have the wrong tag
This is a regression introduced by #1691 
```
$ docker image ls
REPOSITORY                    TAG                 IMAGE ID            CREATED              SIZE
appcelerator/ampagent         0.0.0               c1af2c41e934        About a minute ago   26.4MB
appcelerator/amp-aws          0.0.0               a8dcef6bb775        About a minute ago   16.5MB
appcelerator/amp-local        0.0.0               f6e68bc0c352        About a minute ago   14.7MB
appcelerator/amp-prometheus   0.0.0               4df0850283ff        About a minute ago   125MB
appcelerator/agent            0.0.0               169465485245        About a minute ago   31.8MB
appcelerator/ampbeat          0.0.0               2dfad49d85af        2 minutes ago        23.3MB
appcelerator/gateway          0.0.0               e4d90710a442        2 minutes ago        28.8MB
appcelerator/amplifier        0.0.0               dfd25e5b4033        2 minutes ago        38.7MB
amptools                      latest              bbba2e09044e        2 minutes ago        992MB
appcelerator/amptools         1.9                 0d8f164f60ea        4 hours ago          992MB
alpine                        latest              76da55c8019d        4 weeks ago          3.97MB
appcelerator/prometheus       1.7.1               6f8a89872aa1        3 months ago         104MB
```

### PR DESCRIPTION
**Pull request by bquenin**
Fix #1706 

## How to test
```
$ ampmake clean build
$ docker image ls
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
appcelerator/ampagent         0.16.0-dev          c1af2c41e934        4 minutes ago       26.4MB
appcelerator/amp-aws          0.16.0-dev          a8dcef6bb775        5 minutes ago       16.5MB
appcelerator/amp-local        0.16.0-dev          f6e68bc0c352        5 minutes ago       14.7MB
appcelerator/amp-prometheus   0.16.0-dev          4df0850283ff        5 minutes ago       125MB
appcelerator/agent            0.16.0-dev          169465485245        5 minutes ago       31.8MB
appcelerator/ampbeat          0.16.0-dev          2dfad49d85af        5 minutes ago       23.3MB
appcelerator/gateway          0.16.0-dev          e4d90710a442        6 minutes ago       28.8MB
appcelerator/amplifier        0.16.0-dev          dfd25e5b4033        6 minutes ago       38.7MB
amptools                      latest              bbba2e09044e        6 minutes ago       992MB
appcelerator/amptools         1.9                 0d8f164f60ea        4 hours ago         992MB
alpine                        latest              76da55c8019d        4 weeks ago         3.97MB
appcelerator/prometheus       1.7.1               6f8a89872aa1        3 months ago        104MB
```

### CODE REVIEW

**Comment by ndegory** [comment]
but then, we can't do the `make VERSION=latest build-ampagent` anymore.
the conditional variable assignment is supposed to work, unless the new version of the amptools image doesn't use gnu make.

**Comment by bquenin** [comment]
I don't think anything related to `make` has been changed in the latest version of amptools.

**Comment by ndegory** [comment]
for a reason I ignore, ampmake sets version=0.0.0 and uses it as an env var when it runs docker to set VERSION. I think it's safe to remove this -e line.

**Comment by bquenin** [comment]
Good catch! I'll update accordingly

**Review by ndegory — APPROVED** [review]

**Pull request merged**
