### PR TITLE
359-344-fix stack docker hang

### PR DESCRIPTION
**Pull request by freignat91**
Avoid conditions on which docker hang, see #359 and #344 
To wait for a true docker fix.

test:
- start amp
- execute several times (more than 10): go test -v ./api/rpc/stack

(tested 100 times on ubuntu and os/x)

Warning: tests take more time to be executed.

Regression tests:
- make test
- go test -v ./cmd/amp/cli

### CODE REVIEW

**Review by bquenin — APPROVED** [review]
Tested locally and working on linux.
The tests are taking a looong time though.

**Comment by bquenin** [comment]
```
ok      github.com/appcelerator/amp/api/rpc/logs    17.746s
ok      github.com/appcelerator/amp/api/rpc/service 1.302s
ok      github.com/appcelerator/amp/data/storage/etcd   1.106s
ok      github.com/appcelerator/amp/api/rpc/stack   96.375s
ok      github.com/appcelerator/amp/data/influx 0.003s
ok      github.com/appcelerator/amp/api/rpc/stats   0.197s
ok      github.com/appcelerator/amp/api/rpc/topic   1.056s
```

**Comment by freignat91** [comment]
yes, time due to sequential service start and stop to avoid docker hang. It's temporary.

**Comment by subfuzion** [comment]
@freignat91 Let's hold off a few days before merging this. As of now, with the locked down image versions we're using for the swarm and with latest beta version of Docker for Mac (`Version 1.12.2-beta28 (12906) Channel: Beta`), everything successfully passes for me repeatedly. This fix may no longer be needed. Let's see how testing goes for everyone else for the next day or so.

**Comment by freignat91** [comment]
@Tony, without this fix on Ubuntu or mac you can't execute more than 3 or 4 time the stacks test without getting a Docker hang.

**Comment by subfuzion** [comment]
I think this PR is obsoleted now by Docker 1.13.3-rc1. Let's take another day or so to confirm. Otherwise, let's try the approach I mentioned in chat about serializing access to Docker APIs with a mutex to avoid race conditions for now instead of using delays and retries. Right now, however, it looks like that won't be necessary with this update. Thanks, @freignat91

**Comment by subfuzion** [comment]
Let's close this for now. We can reopen if necessary. Thanks again for the effort, Francois.

**Pull request closed without merging**
