### PR TITLE
Add grpc-gateway and swagger support to proto build

### PR DESCRIPTION
**Pull request by generalhenry**
progress on https://github.com/appcelerator/amp/issues/425

The swagger files are stubs for now, they will fill in as we specify the routes.
Once routes are added the <pkg>.gw.go files will be generated.

Relies on https://github.com/appcelerator/docker-protoc/pull/2

To test:
  clone https://github.com/appcelerator/docker-protoc
  checkout grpc-support
  docker build -t appcelerator/protoc <docker-protoc-dir>
  cd <ampdir>
  make proto

### CODE REVIEW

**Review by chrisccoy — COMMENTED** [review]
LGTM. Probably need another set of eyes on the `hack.proto` changes, but the newly built image seems to be working as prescribed.

**Review by bquenin — APPROVED** [review]
Working on linux

**Comment by bquenin** [comment]
The commands are working, however, the `make proto` command doesn't produce anything new. Is it the expected behavior ?

**Comment by generalhenry** [comment]
@bquenin the only new files should be the `.swagger.json` for now

**Comment by bquenin** [comment]
Ok understood, merging

**Pull request merged**
