### PR TITLE
Post 0.11.0

### PR DESCRIPTION
**Pull request by ndegory**
- Updates from release/0.11
- VERSION bumped to 0.12.0-dev

### CODE REVIEW

**Review by bquenin — CHANGES_REQUESTED** [review]
Looks good, we should probably also update the version on the project homepage.

**Comment by ndegory** [comment]
good catch @bquenin , I forgot it was hardcoded.

**Review by bquenin — DISMISSED** [review]
:+1:

**Review by bquenin — APPROVED** [review]
LGTM

**Pull request merged**
