### PR TITLE
Serverless prototype

### PR DESCRIPTION
**Pull request by bquenin**
Related to #521 

## Verification
    $ amp pf stop
    $ make install
    $ ./shrink.sh local
    $ amp pf start --local
    $ make test

## CLI tests
The source code of the `amp-demo-function` is available here: [amp-demo-function](https://github.com/appcelerator/amp/tree/serverless-proto/examples/functions/demo-function)

    $ docker build -t appcelerator/amp-demo-function examples/functions/demo-function
    [...]

    $ amp function --help
    
    Usage:  amp function COMMAND
    
    function operations
    
    Aliases:
      function, fn
    
    Options:
          --config string   Config file (default is $HOME/.amp.yaml)
      -h, --help            help for function
          --server string   Server address
      -v, --verbose         Verbose output
    
    Commands:
      create      Create a function
      ls          List functions
      rm          Remove function
    
     Run 'amp function COMMAND --help' for more information on a command.

    $ amp fn create -i appcelerator/amp-demo-function test
    [function-id]

    $ amp fn ls
    ID              Name   Image
    [function-id]   test   appcelerator/amp-demo-function   

    $ cat Makefile | curl 127.0.0.1:4242/[function-id] --data-binary @-
    [The result should be a Capitalized Makefile]

    $ amp fn rm [function-id]
    [function-id]

    $ amp fn ls
    ID   Name   Image

### CODE REVIEW

**Review by freignat91 — APPROVED** [review]
LGTM and tests executed ok

**Comment by generalhenry** [comment]
It would be nice if you could use [function-ident] in place of [function-id]

I would also prefer fn.local.atomiq.io (or the like) to localhost:4242 (aka add it to the haproxy config)

**Comment by generalhenry** [comment]
One more small thing, `amp function ls` should have a `-q --quiet` options for `amp function rm $(amp fn ls -q)` cleanups

**Comment by bquenin** [comment]
@generalhenry You're right about the URL, this is only temporary. It should definitely be something like `fn.local.atomiq.io`.
I'll make an update regarding the `-q`.
Regarding function-name vs. function-id, it's just temporary as well, I only built the index by id in etcd.
I'm waiting for feedback on the global approach but all your comments are helpful.
Thanks!

**Comment by bquenin** [comment]
:warning: Also, I think we're hitting a bug in Docker causing the container attachment to fail sporadically, causing the function to fail.
For reference, the bug mentioned is docker/docker#29285

**Comment by bquenin** [comment]
Maybe this issue has an impact as well: docker/docker#29421

**Comment by thaJeztah** [comment]
@bquenin docker 1.12.5 has been released, which contains https://github.com/docker/docker/pull/29424 to resolve the issue you linked to; https://github.com/docker/docker/releases/tag/v1.12.5

**Comment by bquenin** [comment]
@thaJeztah thanks for the feedback. Just tested it with 1.12.5 and now it works like a charm!
:facepunch:

**Comment by subfuzion** [comment]
Thanks @thaJeztah. I would imagine this will land shortly in the next 1.13 RC as well then (we're currently on v1.13.0-rc3).

**Comment by thaJeztah** [comment]
@subfuzion looks like the fix was actually in 1.13.0-rc2 already (see https://github.com/docker/docker/pull/28674); are you having this problem on RC3?

**Comment by bquenin** [comment]
@thaJeztah I tested on latest stable (1.12.5). Going to check on 1.13.0-rc3.

**Comment by thaJeztah** [comment]
Perfect! If you have problems on 1.13, please open an issue in the issue tracker 👍

**Comment by bquenin** [comment]
@thaJeztah Just tested it a thousand times on 1.13.0-rc3, works fine as well! Thanks again

**Comment by thaJeztah** [comment]
Thanks for testing!

**Comment by subfuzion** [comment]
@bquenin Very nice! I'm merging this into v0.5.0-rc1 for additional evaluation. 👍

**Comment by subfuzion** [comment]
@bquenin It looks like there are a few conflicts due to @freignat91 / @ndegory cluster management PR that I just merged into v0.5.0-rc1. Can you work to resolve asap? Thanks!

**Comment by bquenin** [comment]
@subfuzion Ok, I rebased on the branch v0.5.0-rc1

**Comment by subfuzion** [comment]
👍

**Pull request merged**
