### PR TITLE
Update glide deps

### PR DESCRIPTION
**Pull request by subfuzion**
This PR explicitly tags the influx client to match the server version in our image (0.13), and updates the remaining dependencies to the latest versions.

### CODE REVIEW

**Comment by ndegory** [comment]
@subfuzion influxdb 1.0 is not far (planned for summer), we can already start to work on the RC. I'll create a branch but I'll leave master (and latest) on 0.13.

**Comment by subfuzion** [comment]
@ndegory Yes, I was actually testing with `v1.0.0-beta3`. The main thing we have to ensure is to update the entire TICK stack at the same time to maintain version alignment, and then we have to update our glide files (for the client package dependencies).

**Comment by chrisccoy** [comment]
LGTM 
for verification:
make install-deps
make test

**Comment by generalhenry** [comment]
:+1:

**Pull request merged**
