### PR TITLE
[v0.6.x] Adding an example policy and tests to illustrate ladon usage

### PR DESCRIPTION
**Pull request by bquenin**
This PR includes an example usage of Ladon in order to discuss it with the team.

You can run the Ladon test using `make test-unit`.

### CODE REVIEW

**Comment by chrisccoy** [comment]
:+1: The policies seem fairly expressive

**Comment by subfuzion** [comment]
Thanks @bquenin, but please submit [vendor] PRs separate (first) from code PRs. The GitHub UI is way too unwieldy to use for massive PRs.

**Comment by bquenin** [comment]
@subfuzion I submitted a separate vendor PR here #696.
For readability, you can click on the second commit to only see the relevant code: https://github.com/appcelerator/amp/pull/697/commits/91e6864a3d76a97e922062a1e82d8bf4e30c3bf0

**Comment by bquenin** [comment]
Closing this PR until we have a first implementation of the permission model.

**Comment by subfuzion** [comment]
The policy file stuff looks good.

**Pull request closed without merging**
